<a href="https://colab.research.google.com/github/baxronovferuz1/DataScience_Np/blob/main/firstjob.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world,again")

hello world,again


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import seaborn as sns
import torch
import tensorflow as tf
import keras

In [ ]:
np.__version__

'1.26.4'

In [ ]:
import torch

torch.cuda.is_available()

True

In [1]:
import numpy as np

In [2]:
my_list=list(range(20000)) #normal
my_array=np.array(range(20000))  #vektorlashgan



In [3]:
%time for x in range(10): [i*2 for i in my_list]

CPU times: user 13.3 ms, sys: 0 ns, total: 13.3 ms
Wall time: 13.8 ms


In [4]:
%time for x in range(10): my_array*2

CPU times: user 1.27 ms, sys: 0 ns, total: 1.27 ms
Wall time: 3.76 ms


In [5]:
13.8/3.76

3.670212765957447

In [2]:
import numpy as np

In [3]:
list1=[1,4,2,4.5,6,0]
arr1=np.array(list1)

In [4]:
arr1

array([1. , 4. , 2. , 4.5, 6. , 0. ])

In [5]:
import numpy as np

In [6]:
tuple1=(7,5,3.2,5,8,1)
array2=np.array(tuple1)

In [7]:
array2

array([7. , 5. , 3.2, 5. , 8. , 1. ])

In [8]:
arr1.ndim #ndim-array size

1

In [9]:
array2.ndim

1

In [6]:
import numpy as np

In [7]:
data3=[[1,4,2,5],[7,1,3,8]]
arr3=np.array(data3)

In [8]:
arr3

array([[1, 4, 2, 5],
       [7, 1, 3, 8]])

In [9]:
arr3.ndim

2

In [10]:
arr3.shape

(2, 4)

In [11]:
arr3.size

8

In [12]:
import numpy as np

In [14]:
array4=np.zeros((2,4))
array4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
array4=np.ones((2,4))
array4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])