<a href="https://colab.research.google.com/github/baxronovferuz1/DataScience_Np/blob/main/firstjob.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world,again")

hello world,again


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import seaborn as sns
import torch
import tensorflow as tf
import keras

In [ ]:
np.__version__

'1.26.4'

In [ ]:
import torch

torch.cuda.is_available()

True

In [ ]:
import numpy as np

In [ ]:
my_list=list(range(20000)) #normal
my_array=np.array(range(20000))  #vektorlashgan



In [ ]:
%time for x in range(10): [i*2 for i in my_list]

CPU times: user 13.3 ms, sys: 0 ns, total: 13.3 ms
Wall time: 13.8 ms


In [ ]:
%time for x in range(10): my_array*2

CPU times: user 1.27 ms, sys: 0 ns, total: 1.27 ms
Wall time: 3.76 ms


In [ ]:
13.8/3.76

3.670212765957447

In [ ]:
import numpy as np

In [ ]:
list1=[1,4,2,4.5,6,0]
arr1=np.array(list1)

In [ ]:
arr1

array([1. , 4. , 2. , 4.5, 6. , 0. ])

In [ ]:
import numpy as np

In [ ]:
tuple1=(7,5,3.2,5,8,1)
array2=np.array(tuple1)

In [ ]:
array2

array([7. , 5. , 3.2, 5. , 8. , 1. ])

In [ ]:
arr1.ndim #ndim-array size

1

In [ ]:
array2.ndim

1

In [ ]:
import numpy as np

In [ ]:
data3=[[1,4,2,5],[7,1,3,8]]
arr3=np.array(data3)

In [ ]:
arr3

array([[1, 4, 2, 5],
       [7, 1, 3, 8]])

In [ ]:
arr3.ndim

2

In [ ]:
arr3.shape

(2, 4)

In [ ]:
arr3.size

8

In [ ]:
import numpy as np

In [ ]:
array4=np.zeros((2,4))
array4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
array4=np.ones((2,4))
array4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr5=np.array([5,2,9,0,3], dtype=np.float64)
arr5

array([5., 2., 9., 0., 3.])

In [ ]:
arr6=np.array([3,2,4,5,8], dtype=np.int32)
arr6

array([3, 2, 4, 5, 8], dtype=int32)

In [ ]:
arr5.dtype

dtype('float64')

In [ ]:
arr7=np.array([1,2,4,5,6]) #avtomatic -int64 type
arr7

array([1, 2, 4, 5, 6])

In [ ]:
arr7.dtype

dtype('int64')

In [ ]:
float_array=arr7.astype(np.float64)
float_array.dtype

dtype('float64')

In [ ]:
arr8=np.array([1.2,3.2,4.5,6.5])

In [ ]:
arr8.dtype

dtype('float64')

In [ ]:
int_arr=arr8.astype(np.int64)

In [ ]:
int_arr.dtype

dtype('int64')

In [ ]:
arr9=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr9

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr9[1,1]

5

In [ ]:
arr10=arr9[2,1:3]
arr10

array([8, 9])

In [ ]:
arr10=np.array(["Ali","Vali","Abdusamad","Hasan","Husan","Bekzod","Shohruh"])


In [ ]:
r_data=np.random.randn(7,3)

In [ ]:
r_data

array([[ 0.47586549, -0.50118118, -0.30165911],
       [ 1.4099227 ,  0.36312282, -1.2895044 ],
       [-0.31525302, -1.32834907,  0.26379727],
       [ 0.92372834, -1.05435786,  1.74970365],
       [-0.23962443, -0.60707214, -1.12318633],
       [ 1.28102636,  0.5164728 ,  0.77598974],
       [ 1.37305013,  0.13706048,  0.43234968]])

In [ ]:
r_data[arr10=="Husan"]

array([[-0.23962443, -0.60707214, -1.12318633]])

In [ ]:
r_data[arr10 != "Vali"]

array([[ 0.47586549, -0.50118118, -0.30165911],
       [-0.31525302, -1.32834907,  0.26379727],
       [ 0.92372834, -1.05435786,  1.74970365],
       [-0.23962443, -0.60707214, -1.12318633],
       [ 1.28102636,  0.5164728 ,  0.77598974],
       [ 1.37305013,  0.13706048,  0.43234968]])

In [ ]:
r_data[~(arr10=="Bekzod")]

array([[ 0.47586549, -0.50118118, -0.30165911],
       [ 1.4099227 ,  0.36312282, -1.2895044 ],
       [-0.31525302, -1.32834907,  0.26379727],
       [ 0.92372834, -1.05435786,  1.74970365],
       [-0.23962443, -0.60707214, -1.12318633],
       [ 1.37305013,  0.13706048,  0.43234968]])

In [ ]:
arr11=(arr10=="Ali") | (arr10=="Vali")
arr11

array([ True,  True, False, False, False, False, False])

In [ ]:
r_data[arr11]

array([[ 0.47586549, -0.50118118, -0.30165911],
       [ 1.4099227 ,  0.36312282, -1.2895044 ]])

In [ ]:
r_data

array([[ 0.47586549, -0.50118118, -0.30165911],
       [ 1.4099227 ,  0.36312282, -1.2895044 ],
       [-0.31525302, -1.32834907,  0.26379727],
       [ 0.92372834, -1.05435786,  1.74970365],
       [-0.23962443, -0.60707214, -1.12318633],
       [ 1.28102636,  0.5164728 ,  0.77598974],
       [ 1.37305013,  0.13706048,  0.43234968]])

In [ ]:
r_data[r_data<0]

array([-0.50118118, -0.30165911, -1.2895044 , -0.31525302, -1.32834907,
       -1.05435786, -0.23962443, -0.60707214, -1.12318633])

In [ ]:
r_data[r_data<0]=0

In [ ]:
r_data

array([[0.47586549, 0.        , 0.        ],
       [1.4099227 , 0.36312282, 0.        ],
       [0.        , 0.        , 0.26379727],
       [0.92372834, 0.        , 1.74970365],
       [0.        , 0.        , 0.        ],
       [1.28102636, 0.5164728 , 0.77598974],
       [1.37305013, 0.13706048, 0.43234968]])

In [ ]:
arr12=np.arange(6).reshape(3,2)

In [ ]:
arr12

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr12.T #Transpose

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
np.dot(arr12,arr12.T)

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

In [1]:
import numpy as np

In [2]:
arr13=np.arange(8)

In [3]:
np.sqrt(arr13) #Unary-sqrt,square,exp,log,modf,sign,isnan

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [4]:
np.square(arr13)

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [5]:
np.exp(arr13)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [6]:
np.log(arr13)

<ipython-input-6-807d863ebc7e>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr13)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015])

In [7]:
np.log(arr13[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015])

In [8]:
arr14=np.random.randn(5)
arr14

array([-1.2019784 ,  0.87481513,  0.25801803, -0.78428618,  0.19160698])

In [9]:
b_arr,q_arr=np.modf(arr14)

In [10]:
print(b_arr)
print(q_arr)

[-0.2019784   0.87481513  0.25801803 -0.78428618  0.19160698]
[-1.  0.  0. -0.  0.]


In [11]:
np.sign(arr14)

array([-1.,  1.,  1., -1.,  1.])

In [12]:
np.isnan(arr14)

array([False, False, False, False, False])

In [13]:
arr14[1]=np.NaN

In [14]:
np.isnan(arr14)

array([False,  True, False, False, False])

In [15]:
arr15=np.random.randn(5)
arr16=np.random.randn(5)

In [16]:
np.add(arr15,arr16) #Binary-add,multiply,maximum...

array([-0.67949659, -0.57622437,  2.35193888,  1.00664985, -2.30427755])

In [17]:
arr15+arr16

array([-0.67949659, -0.57622437,  2.35193888,  1.00664985, -2.30427755])

In [18]:
np.multiply(arr15,arr16)

array([-0.7632123 , -0.81743198,  0.64796804, -0.56725696, -0.48232697])

In [19]:
np.maximum(arr15,arr16)

array([0.59761034, 0.66080331, 2.03325357, 1.40919078, 0.19313099])

In [20]:
arr15

array([ 0.59761034, -1.23702768,  2.03325357,  1.40919078, -2.49740853])

In [21]:
arr16

array([-1.27710692,  0.66080331,  0.31868531, -0.40254092,  0.19313099])

In [22]:
x_arr=np.array([1.1,1.2,1.3,1.4,1.5])
y_arr=np.array([2.1,2.2,2.3,2.4,2.5])


In [23]:
cond=np.array([True,False,True,True,False])

In [26]:
r_arr=np.where(cond,x_arr,y_arr)
r_arr

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [29]:
arr=np.random.randn(3,3)
arr

array([[ 1.97028118,  0.14300352,  0.52961907],
       [-0.2465072 , -0.09380681,  0.62256699],
       [ 1.46297638,  0.09431839,  0.39675445]])

In [30]:
result=np.where(arr<0,-1,1)
result

array([[ 1,  1,  1],
       [-1, -1,  1],
       [ 1,  1,  1]])