<a href="https://colab.research.google.com/github/baxronovferuz1/DataScience_Np/blob/main/firstjob.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world,again")

hello world,again


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import seaborn as sns
import torch
import tensorflow as tf
import keras

In [ ]:
np.__version__

'1.26.4'

In [ ]:
import torch

torch.cuda.is_available()

True

In [ ]:
import numpy as np

In [ ]:
my_list=list(range(20000)) #normal
my_array=np.array(range(20000))  #vektorlashgan



In [ ]:
%time for x in range(10): [i*2 for i in my_list]

CPU times: user 13.3 ms, sys: 0 ns, total: 13.3 ms
Wall time: 13.8 ms


In [ ]:
%time for x in range(10): my_array*2

CPU times: user 1.27 ms, sys: 0 ns, total: 1.27 ms
Wall time: 3.76 ms


In [ ]:
13.8/3.76

3.670212765957447

In [ ]:
import numpy as np

In [ ]:
list1=[1,4,2,4.5,6,0]
arr1=np.array(list1)

In [ ]:
arr1

array([1. , 4. , 2. , 4.5, 6. , 0. ])

In [ ]:
import numpy as np

In [ ]:
tuple1=(7,5,3.2,5,8,1)
array2=np.array(tuple1)

In [ ]:
array2

array([7. , 5. , 3.2, 5. , 8. , 1. ])

In [ ]:
arr1.ndim #ndim-array size

1

In [ ]:
array2.ndim

1

In [ ]:
import numpy as np

In [ ]:
data3=[[1,4,2,5],[7,1,3,8]]
arr3=np.array(data3)

In [ ]:
arr3

array([[1, 4, 2, 5],
       [7, 1, 3, 8]])

In [ ]:
arr3.ndim

2

In [ ]:
arr3.shape

(2, 4)

In [ ]:
arr3.size

8

In [ ]:
import numpy as np

In [ ]:
array4=np.zeros((2,4))
array4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
array4=np.ones((2,4))
array4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr5=np.array([5,2,9,0,3], dtype=np.float64)
arr5

array([5., 2., 9., 0., 3.])

In [ ]:
arr6=np.array([3,2,4,5,8], dtype=np.int32)
arr6

array([3, 2, 4, 5, 8], dtype=int32)

In [ ]:
arr5.dtype

dtype('float64')

In [ ]:
arr7=np.array([1,2,4,5,6]) #avtomatic -int64 type
arr7

array([1, 2, 4, 5, 6])

In [ ]:
arr7.dtype

dtype('int64')

In [ ]:
float_array=arr7.astype(np.float64)
float_array.dtype

dtype('float64')

In [ ]:
arr8=np.array([1.2,3.2,4.5,6.5])

In [ ]:
arr8.dtype

dtype('float64')

In [ ]:
int_arr=arr8.astype(np.int64)

In [ ]:
int_arr.dtype

dtype('int64')

In [ ]:
arr9=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr9

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr9[1,1]

5

In [ ]:
arr10=arr9[2,1:3]
arr10

array([8, 9])

In [ ]:
arr10=np.array(["Ali","Vali","Abdusamad","Hasan","Husan","Bekzod","Shohruh"])


In [ ]:
r_data=np.random.randn(7,3)

In [ ]:
r_data

array([[ 0.47586549, -0.50118118, -0.30165911],
       [ 1.4099227 ,  0.36312282, -1.2895044 ],
       [-0.31525302, -1.32834907,  0.26379727],
       [ 0.92372834, -1.05435786,  1.74970365],
       [-0.23962443, -0.60707214, -1.12318633],
       [ 1.28102636,  0.5164728 ,  0.77598974],
       [ 1.37305013,  0.13706048,  0.43234968]])

In [ ]:
r_data[arr10=="Husan"]

array([[-0.23962443, -0.60707214, -1.12318633]])

In [ ]:
r_data[arr10 != "Vali"]

array([[ 0.47586549, -0.50118118, -0.30165911],
       [-0.31525302, -1.32834907,  0.26379727],
       [ 0.92372834, -1.05435786,  1.74970365],
       [-0.23962443, -0.60707214, -1.12318633],
       [ 1.28102636,  0.5164728 ,  0.77598974],
       [ 1.37305013,  0.13706048,  0.43234968]])

In [ ]:
r_data[~(arr10=="Bekzod")]

array([[ 0.47586549, -0.50118118, -0.30165911],
       [ 1.4099227 ,  0.36312282, -1.2895044 ],
       [-0.31525302, -1.32834907,  0.26379727],
       [ 0.92372834, -1.05435786,  1.74970365],
       [-0.23962443, -0.60707214, -1.12318633],
       [ 1.37305013,  0.13706048,  0.43234968]])

In [ ]:
arr11=(arr10=="Ali") | (arr10=="Vali")
arr11

array([ True,  True, False, False, False, False, False])

In [ ]:
r_data[arr11]

array([[ 0.47586549, -0.50118118, -0.30165911],
       [ 1.4099227 ,  0.36312282, -1.2895044 ]])

In [ ]:
r_data

array([[ 0.47586549, -0.50118118, -0.30165911],
       [ 1.4099227 ,  0.36312282, -1.2895044 ],
       [-0.31525302, -1.32834907,  0.26379727],
       [ 0.92372834, -1.05435786,  1.74970365],
       [-0.23962443, -0.60707214, -1.12318633],
       [ 1.28102636,  0.5164728 ,  0.77598974],
       [ 1.37305013,  0.13706048,  0.43234968]])

In [ ]:
r_data[r_data<0]

array([-0.50118118, -0.30165911, -1.2895044 , -0.31525302, -1.32834907,
       -1.05435786, -0.23962443, -0.60707214, -1.12318633])

In [ ]:
r_data[r_data<0]=0

In [ ]:
r_data

array([[0.47586549, 0.        , 0.        ],
       [1.4099227 , 0.36312282, 0.        ],
       [0.        , 0.        , 0.26379727],
       [0.92372834, 0.        , 1.74970365],
       [0.        , 0.        , 0.        ],
       [1.28102636, 0.5164728 , 0.77598974],
       [1.37305013, 0.13706048, 0.43234968]])

In [ ]:
arr12=np.arange(6).reshape(3,2)

In [ ]:
arr12

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr12.T #Transpose

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
np.dot(arr12,arr12.T)

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

In [ ]:
import numpy as np

In [ ]:
arr13=np.arange(8)

In [ ]:
np.sqrt(arr13) #Unary-sqrt,square,exp,log,modf,sign,isnan

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [ ]:
np.square(arr13)

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [ ]:
np.exp(arr13)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [ ]:
np.log(arr13)

<ipython-input-6-807d863ebc7e>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr13)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015])

In [ ]:
np.log(arr13[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015])

In [ ]:
arr14=np.random.randn(5)
arr14

array([-1.2019784 ,  0.87481513,  0.25801803, -0.78428618,  0.19160698])

In [ ]:
b_arr,q_arr=np.modf(arr14)

In [ ]:
print(b_arr)
print(q_arr)

[-0.2019784   0.87481513  0.25801803 -0.78428618  0.19160698]
[-1.  0.  0. -0.  0.]


In [ ]:
np.sign(arr14)

array([-1.,  1.,  1., -1.,  1.])

In [ ]:
np.isnan(arr14)

array([False, False, False, False, False])

In [ ]:
arr14[1]=np.NaN

In [ ]:
np.isnan(arr14)

array([False,  True, False, False, False])

In [ ]:
arr15=np.random.randn(5)
arr16=np.random.randn(5)

In [ ]:
np.add(arr15,arr16) #Binary-add,multiply,maximum...

array([-0.67949659, -0.57622437,  2.35193888,  1.00664985, -2.30427755])

In [ ]:
arr15+arr16

array([-0.67949659, -0.57622437,  2.35193888,  1.00664985, -2.30427755])

In [ ]:
np.multiply(arr15,arr16)

array([-0.7632123 , -0.81743198,  0.64796804, -0.56725696, -0.48232697])

In [ ]:
np.maximum(arr15,arr16)

array([0.59761034, 0.66080331, 2.03325357, 1.40919078, 0.19313099])

In [ ]:
arr15

array([ 0.59761034, -1.23702768,  2.03325357,  1.40919078, -2.49740853])

In [ ]:
arr16

array([-1.27710692,  0.66080331,  0.31868531, -0.40254092,  0.19313099])

In [ ]:
x_arr=np.array([1.1,1.2,1.3,1.4,1.5])
y_arr=np.array([2.1,2.2,2.3,2.4,2.5])


In [ ]:
cond=np.array([True,False,True,True,False])

In [ ]:
r_arr=np.where(cond,x_arr,y_arr)
r_arr

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [ ]:
arr=np.random.randn(3,3)
arr

array([[ 1.97028118,  0.14300352,  0.52961907],
       [-0.2465072 , -0.09380681,  0.62256699],
       [ 1.46297638,  0.09431839,  0.39675445]])

In [ ]:
result=np.where(arr<0,-1,1)
result

array([[ 1,  1,  1],
       [-1, -1,  1],
       [ 1,  1,  1]])

In [ ]:
arr17=np.random.randn(6,4)
arr17

array([[-0.24332698, -1.53945971, -0.51911703,  0.06716126],
       [-1.32102032,  0.81448664, -0.44454831,  0.0097889 ],
       [ 0.19907587, -0.56617042, -0.39279017,  1.03718558],
       [ 1.10382281,  0.05465317,  0.80834391,  1.33934714],
       [-1.68169702,  0.37352933,  1.11895168,  0.9918056 ],
       [-0.41669942, -1.1587718 ,  0.55296736, -2.10538208]])

In [ ]:
arr17.sum()

5.544569559166768

In [ ]:
arr17.sum(axis=1) #by row

array([ 0.34614457,  0.34245171,  0.24698038,  2.36459896, -0.73338571,
        2.97777964])

In [ ]:
arr17.sum(axis=0) #by column

array([ 0.13381732,  6.75976002, -1.03574966, -0.31325812])

In [ ]:
np.mean(arr17)

-0.07991100015101295

In [ ]:
arr17.mean()

-0.07991100015101295

In [ ]:
arr17.mean(axis=1)

array([-0.55868561, -0.23532327,  0.06932521,  0.82654176,  0.2006474 ,
       -0.78197149])

In [ ]:
arr17.mean(axis=0)

array([-0.39330751, -0.33695546,  0.18730124,  0.22331773])

In [ ]:
arr18=np.arange(6)
arr18

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr18.cumsum()

array([ 0,  1,  3,  6, 10, 15])

In [ ]:
arr19=np.random.randn(6)
arr19

array([-0.52103461,  0.93784467, -0.43476107,  2.03529266, -0.18894129,
       -0.67234901])

In [ ]:
sort_arr=np.sort(arr19)
sort_arr

array([-0.67234901, -0.52103461, -0.43476107, -0.18894129,  0.93784467,
        2.03529266])

In [ ]:
reverse_sort=-np.sort(-arr19) #reverse sort

In [ ]:
reverse_sort

array([ 2.03529266,  0.93784467, -0.18894129, -0.43476107, -0.52103461,
       -0.67234901])

In [ ]:
arr20=np.random.randn(3,4)
arr20

array([[-0.80863969,  0.86943897,  0.3678431 , -0.30254195],
       [ 0.24058725,  0.64709697,  0.86422134, -0.90795647],
       [ 0.47389365, -0.51628005,  0.67993507,  0.30687938]])

In [ ]:
row_sort=np.sort(arr20,axis=0)
row_sort

array([[-0.80863969, -0.51628005,  0.3678431 , -0.90795647],
       [ 0.24058725,  0.64709697,  0.67993507, -0.30254195],
       [ 0.47389365,  0.86943897,  0.86422134,  0.30687938]])

In [ ]:
column_sort=np.sort(arr20,axis=0)
column_sort

array([[-0.80863969, -0.51628005,  0.3678431 , -0.90795647],
       [ 0.24058725,  0.64709697,  0.67993507, -0.30254195],
       [ 0.47389365,  0.86943897,  0.86422134,  0.30687938]])

In [ ]:
arr21=np.array([1,3,2,3,4,8,4,6,1])


In [ ]:
np.unique(arr21)

array([1, 2, 3, 4, 6, 8])

In [ ]:
arr22=np.array([1,3,2,3,4,8,4,6,1])
arr23=np.array([0,1,2,3])

In [ ]:
result_arr=np.in1d(arr22,arr23)
result_arr

array([ True,  True,  True,  True, False, False, False, False,  True])

In [ ]:
np.setdiff1d(arr22,arr23)

array([4, 6, 8])

In [ ]:
import numpy as np

In [ ]:
arr24=np.arange(10)
np.save("data",arr24)


In [3]:
arr24_=np.load("data.npy")
arr24_

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr25=np.arange(15)


In [5]:
np.savez("array",a=arr24,b=arr25)


In [8]:
arrays=np.load("array.npz")
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
np.savez_compressed("array_comp", a=arr24, b=arr25)