<a href="https://colab.research.google.com/github/baxronovferuz1/DataScience_Np/blob/main/Numpy_Pandas_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world,again")

hello world,again


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import seaborn as sns
import torch
import tensorflow as tf
import keras

In [ ]:
np.__version__

'1.26.4'

In [ ]:
import torch

torch.cuda.is_available()

True

In [ ]:
import numpy as np

In [ ]:
my_list=list(range(20000)) #normal
my_array=np.array(range(20000))  #vektorlashgan



In [ ]:
%time for x in range(10): [i*2 for i in my_list]

CPU times: user 13.3 ms, sys: 0 ns, total: 13.3 ms
Wall time: 13.8 ms


In [ ]:
%time for x in range(10): my_array*2

CPU times: user 1.27 ms, sys: 0 ns, total: 1.27 ms
Wall time: 3.76 ms


In [ ]:
13.8/3.76

3.670212765957447

In [ ]:
import numpy as np

In [ ]:
list1=[1,4,2,4.5,6,0]
arr1=np.array(list1)

In [ ]:
arr1

array([1. , 4. , 2. , 4.5, 6. , 0. ])

In [ ]:
import numpy as np

In [ ]:
tuple1=(7,5,3.2,5,8,1)
array2=np.array(tuple1)

In [ ]:
array2

array([7. , 5. , 3.2, 5. , 8. , 1. ])

In [ ]:
arr1.ndim #ndim-array size

1

In [ ]:
array2.ndim

1

In [ ]:
import numpy as np

In [ ]:
data3=[[1,4,2,5],[7,1,3,8]]
arr3=np.array(data3)

In [ ]:
arr3

array([[1, 4, 2, 5],
       [7, 1, 3, 8]])

In [ ]:
arr3.ndim

2

In [ ]:
arr3.shape

(2, 4)

In [ ]:
arr3.size

8

In [ ]:
import numpy as np

In [ ]:
array4=np.zeros((2,4))
array4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
array4=np.ones((2,4))
array4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr5=np.array([5,2,9,0,3], dtype=np.float64)
arr5

array([5., 2., 9., 0., 3.])

In [ ]:
arr6=np.array([3,2,4,5,8], dtype=np.int32)
arr6

array([3, 2, 4, 5, 8], dtype=int32)

In [ ]:
arr5.dtype

dtype('float64')

In [ ]:
arr7=np.array([1,2,4,5,6]) #avtomatic -int64 type
arr7

array([1, 2, 4, 5, 6])

In [ ]:
arr7.dtype

dtype('int64')

In [ ]:
float_array=arr7.astype(np.float64)
float_array.dtype

dtype('float64')

In [ ]:
arr8=np.array([1.2,3.2,4.5,6.5])

In [ ]:
arr8.dtype

dtype('float64')

In [ ]:
int_arr=arr8.astype(np.int64)

In [ ]:
int_arr.dtype

dtype('int64')

In [ ]:
arr9=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr9

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr9[1,1]

5

In [ ]:
arr10=arr9[2,1:3]
arr10

array([8, 9])

In [ ]:
arr10=np.array(["Ali","Vali","Abdusamad","Hasan","Husan","Bekzod","Shohruh"])


In [ ]:
r_data=np.random.randn(7,3)

In [ ]:
r_data

array([[ 0.47586549, -0.50118118, -0.30165911],
       [ 1.4099227 ,  0.36312282, -1.2895044 ],
       [-0.31525302, -1.32834907,  0.26379727],
       [ 0.92372834, -1.05435786,  1.74970365],
       [-0.23962443, -0.60707214, -1.12318633],
       [ 1.28102636,  0.5164728 ,  0.77598974],
       [ 1.37305013,  0.13706048,  0.43234968]])

In [ ]:
r_data[arr10=="Husan"]

array([[-0.23962443, -0.60707214, -1.12318633]])

In [ ]:
r_data[arr10 != "Vali"]

array([[ 0.47586549, -0.50118118, -0.30165911],
       [-0.31525302, -1.32834907,  0.26379727],
       [ 0.92372834, -1.05435786,  1.74970365],
       [-0.23962443, -0.60707214, -1.12318633],
       [ 1.28102636,  0.5164728 ,  0.77598974],
       [ 1.37305013,  0.13706048,  0.43234968]])

In [ ]:
r_data[~(arr10=="Bekzod")]

array([[ 0.47586549, -0.50118118, -0.30165911],
       [ 1.4099227 ,  0.36312282, -1.2895044 ],
       [-0.31525302, -1.32834907,  0.26379727],
       [ 0.92372834, -1.05435786,  1.74970365],
       [-0.23962443, -0.60707214, -1.12318633],
       [ 1.37305013,  0.13706048,  0.43234968]])

In [ ]:
arr11=(arr10=="Ali") | (arr10=="Vali")
arr11

array([ True,  True, False, False, False, False, False])

In [ ]:
r_data[arr11]

array([[ 0.47586549, -0.50118118, -0.30165911],
       [ 1.4099227 ,  0.36312282, -1.2895044 ]])

In [ ]:
r_data

array([[ 0.47586549, -0.50118118, -0.30165911],
       [ 1.4099227 ,  0.36312282, -1.2895044 ],
       [-0.31525302, -1.32834907,  0.26379727],
       [ 0.92372834, -1.05435786,  1.74970365],
       [-0.23962443, -0.60707214, -1.12318633],
       [ 1.28102636,  0.5164728 ,  0.77598974],
       [ 1.37305013,  0.13706048,  0.43234968]])

In [ ]:
r_data[r_data<0]

array([-0.50118118, -0.30165911, -1.2895044 , -0.31525302, -1.32834907,
       -1.05435786, -0.23962443, -0.60707214, -1.12318633])

In [ ]:
r_data[r_data<0]=0

In [ ]:
r_data

array([[0.47586549, 0.        , 0.        ],
       [1.4099227 , 0.36312282, 0.        ],
       [0.        , 0.        , 0.26379727],
       [0.92372834, 0.        , 1.74970365],
       [0.        , 0.        , 0.        ],
       [1.28102636, 0.5164728 , 0.77598974],
       [1.37305013, 0.13706048, 0.43234968]])

In [ ]:
arr12=np.arange(6).reshape(3,2)

In [ ]:
arr12

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr12.T #Transpose

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
np.dot(arr12,arr12.T)

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

In [ ]:
import numpy as np

In [ ]:
arr13=np.arange(8)

In [ ]:
np.sqrt(arr13) #Unary-sqrt,square,exp,log,modf,sign,isnan

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [ ]:
np.square(arr13)

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [ ]:
np.exp(arr13)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [ ]:
np.log(arr13)

<ipython-input-6-807d863ebc7e>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr13)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015])

In [ ]:
np.log(arr13[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015])

In [ ]:
arr14=np.random.randn(5)
arr14

array([-1.2019784 ,  0.87481513,  0.25801803, -0.78428618,  0.19160698])

In [ ]:
b_arr,q_arr=np.modf(arr14)

In [ ]:
print(b_arr)
print(q_arr)

[-0.2019784   0.87481513  0.25801803 -0.78428618  0.19160698]
[-1.  0.  0. -0.  0.]


In [ ]:
np.sign(arr14)

array([-1.,  1.,  1., -1.,  1.])

In [ ]:
np.isnan(arr14)

array([False, False, False, False, False])

In [ ]:
arr14[1]=np.NaN

In [ ]:
np.isnan(arr14)

array([False,  True, False, False, False])

In [ ]:
arr15=np.random.randn(5)
arr16=np.random.randn(5)

In [ ]:
np.add(arr15,arr16) #Binary-add,multiply,maximum...

array([-0.67949659, -0.57622437,  2.35193888,  1.00664985, -2.30427755])

In [ ]:
arr15+arr16

array([-0.67949659, -0.57622437,  2.35193888,  1.00664985, -2.30427755])

In [ ]:
np.multiply(arr15,arr16)

array([-0.7632123 , -0.81743198,  0.64796804, -0.56725696, -0.48232697])

In [ ]:
np.maximum(arr15,arr16)

array([0.59761034, 0.66080331, 2.03325357, 1.40919078, 0.19313099])

In [ ]:
arr15

array([ 0.59761034, -1.23702768,  2.03325357,  1.40919078, -2.49740853])

In [ ]:
arr16

array([-1.27710692,  0.66080331,  0.31868531, -0.40254092,  0.19313099])

In [ ]:
x_arr=np.array([1.1,1.2,1.3,1.4,1.5])
y_arr=np.array([2.1,2.2,2.3,2.4,2.5])


In [ ]:
cond=np.array([True,False,True,True,False])

In [ ]:
r_arr=np.where(cond,x_arr,y_arr)
r_arr

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [ ]:
arr=np.random.randn(3,3)
arr

array([[ 1.97028118,  0.14300352,  0.52961907],
       [-0.2465072 , -0.09380681,  0.62256699],
       [ 1.46297638,  0.09431839,  0.39675445]])

In [ ]:
result=np.where(arr<0,-1,1)
result

array([[ 1,  1,  1],
       [-1, -1,  1],
       [ 1,  1,  1]])

In [ ]:
arr17=np.random.randn(6,4)
arr17

array([[-0.24332698, -1.53945971, -0.51911703,  0.06716126],
       [-1.32102032,  0.81448664, -0.44454831,  0.0097889 ],
       [ 0.19907587, -0.56617042, -0.39279017,  1.03718558],
       [ 1.10382281,  0.05465317,  0.80834391,  1.33934714],
       [-1.68169702,  0.37352933,  1.11895168,  0.9918056 ],
       [-0.41669942, -1.1587718 ,  0.55296736, -2.10538208]])

In [ ]:
arr17.sum()

5.544569559166768

In [ ]:
arr17.sum(axis=1) #by row

array([ 0.34614457,  0.34245171,  0.24698038,  2.36459896, -0.73338571,
        2.97777964])

In [ ]:
arr17.sum(axis=0) #by column

array([ 0.13381732,  6.75976002, -1.03574966, -0.31325812])

In [ ]:
np.mean(arr17)

-0.07991100015101295

In [ ]:
arr17.mean()

-0.07991100015101295

In [ ]:
arr17.mean(axis=1)

array([-0.55868561, -0.23532327,  0.06932521,  0.82654176,  0.2006474 ,
       -0.78197149])

In [ ]:
arr17.mean(axis=0)

array([-0.39330751, -0.33695546,  0.18730124,  0.22331773])

In [ ]:
arr18=np.arange(6)
arr18

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr18.cumsum()

array([ 0,  1,  3,  6, 10, 15])

In [ ]:
arr19=np.random.randn(6)
arr19

array([-0.52103461,  0.93784467, -0.43476107,  2.03529266, -0.18894129,
       -0.67234901])

In [ ]:
sort_arr=np.sort(arr19)
sort_arr

array([-0.67234901, -0.52103461, -0.43476107, -0.18894129,  0.93784467,
        2.03529266])

In [ ]:
reverse_sort=-np.sort(-arr19) #reverse sort

In [ ]:
reverse_sort

array([ 2.03529266,  0.93784467, -0.18894129, -0.43476107, -0.52103461,
       -0.67234901])

In [ ]:
arr20=np.random.randn(3,4)
arr20

array([[-0.80863969,  0.86943897,  0.3678431 , -0.30254195],
       [ 0.24058725,  0.64709697,  0.86422134, -0.90795647],
       [ 0.47389365, -0.51628005,  0.67993507,  0.30687938]])

In [ ]:
row_sort=np.sort(arr20,axis=0)
row_sort

array([[-0.80863969, -0.51628005,  0.3678431 , -0.90795647],
       [ 0.24058725,  0.64709697,  0.67993507, -0.30254195],
       [ 0.47389365,  0.86943897,  0.86422134,  0.30687938]])

In [ ]:
column_sort=np.sort(arr20,axis=0)
column_sort

array([[-0.80863969, -0.51628005,  0.3678431 , -0.90795647],
       [ 0.24058725,  0.64709697,  0.67993507, -0.30254195],
       [ 0.47389365,  0.86943897,  0.86422134,  0.30687938]])

In [ ]:
arr21=np.array([1,3,2,3,4,8,4,6,1])


In [ ]:
np.unique(arr21)

array([1, 2, 3, 4, 6, 8])

In [ ]:
arr22=np.array([1,3,2,3,4,8,4,6,1])
arr23=np.array([0,1,2,3])

In [ ]:
result_arr=np.in1d(arr22,arr23)
result_arr

array([ True,  True,  True,  True, False, False, False, False,  True])

In [ ]:
np.setdiff1d(arr22,arr23)

array([4, 6, 8])

In [ ]:
import numpy as np

In [ ]:
arr24=np.arange(10)
np.save("data",arr24)


In [ ]:
arr24_=np.load("data.npy")
arr24_

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr25=np.arange(15)


In [ ]:
np.savez("array",a=arr24,b=arr25)


In [ ]:
arrays=np.load("array.npz")
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.savez_compressed("array_comp", a=arr24, b=arr25)

In [ ]:
import pandas as pd
import numpy as np
from pandas import Series

In [ ]:
obj=Series([1,4,6.7,5.9,3])
type(obj)

In [ ]:
print(obj)

0    1.0
1    4.0
2    6.7
3    5.9
4    3.0
dtype: float64


In [ ]:
obj.values

array([1. , 4. , 6.7, 5.9, 3. ])

In [ ]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
obj[2]

6.7

In [ ]:
obj1=Series([1,4,6.7,5.9,3], index=["a","b","c","d","e"])
print(obj1)

a    1.0
b    4.0
c    6.7
d    5.9
e    3.0
dtype: float64


In [ ]:
obj1.values


array([1. , 4. , 6.7, 5.9, 3. ])

In [ ]:
obj1.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [ ]:
obj1["a"]

1.0

In [ ]:
obj1[obj1<4]

a    1.0
e    3.0
dtype: float64

In [ ]:
obj1*2

a     2.0
b     8.0
c    13.4
d    11.8
e     6.0
dtype: float64

In [ ]:
obj2={"Ali":2001,"Vali":2002,"Hasan":1999,"Husan":1998}
result_obj=Series(obj2)
result_obj

Ali      2001
Vali     2002
Hasan    1999
Husan    1998
dtype: int64

In [ ]:
format_obj=["Vali","Husan","Ali","Hasan","Rustam","Xurshid"]

In [ ]:
obj3=Series(obj2, index=format_obj)

In [ ]:
obj3

Vali       2002.0
Husan      1998.0
Ali        2001.0
Hasan      1999.0
Rustam        NaN
Xurshid       NaN
dtype: float64

In [ ]:
obj3.isnull()

Vali       False
Husan      False
Ali        False
Hasan      False
Rustam      True
Xurshid     True
dtype: bool

In [ ]:
obj3.notnull()

Vali        True
Husan       True
Ali         True
Hasan       True
Rustam     False
Xurshid    False
dtype: bool

In [ ]:
obj3.index.name="Year of birth"

In [ ]:
obj3

Year of birth
Vali       2002.0
Husan      1998.0
Ali        2001.0
Hasan      1999.0
Rustam        NaN
Xurshid       NaN
dtype: float64

In [ ]:
obj3.name="User information"

In [ ]:
obj3

Year of birth
Vali       2002.0
Husan      1998.0
Ali        2001.0
Hasan      1999.0
Rustam        NaN
Xurshid       NaN
Name: User information, dtype: float64

In [ ]:
obj4={
    "Year":[2024,2020,2018,2015,2012],
    "Population":[34.3,31.4,28.5,25.6,23.4],
    "Temp":[1.92,1.85,1.74,1.72,1.69]
}

r_obj=pd.DataFrame(obj4)

In [ ]:
r_obj

Year  Population  Temp
0  2024        34.3  1.92
1  2020        31.4  1.85
2  2018        28.5  1.74
3  2015        25.6  1.72
4  2012        23.4  1.69

In [ ]:
r_obj.head(3)

Year  Population  Temp
0  2024        34.3  1.92
1  2020        31.4  1.85
2  2018        28.5  1.74

In [ ]:
r_obj.shape

(5, 3)

In [ ]:
obj5=pd.DataFrame(obj4, columns=["Temp","Population","Year","Percent"])
obj5

Temp  Population  Year Percent
0  1.92        34.3  2024     NaN
1  1.85        31.4  2020     NaN
2  1.74        28.5  2018     NaN
3  1.72        25.6  2015     NaN
4  1.69        23.4  2012     NaN

In [ ]:
obj5=pd.DataFrame(obj4, columns=["Temp","Population","Year","Percent"], index=["one","two","three","four","five"])

In [ ]:
obj5

Temp  Population  Year Percent
one    1.92        34.3  2024     NaN
two    1.85        31.4  2020     NaN
three  1.74        28.5  2018     NaN
four   1.72        25.6  2015     NaN
five   1.69        23.4  2012     NaN

In [ ]:
obj5.Percent=50
obj5

Temp  Population  Year  Percent
one    1.92        34.3  2024       50
two    1.85        31.4  2020       50
three  1.74        28.5  2018       50
four   1.72        25.6  2015       50
five   1.69        23.4  2012       50

In [ ]:
obj6=pd.Series([25,30,57], index=["two","four","one"])
obj6

two     25
four    30
one     57
dtype: int64

In [ ]:
obj5.Percent=obj6
obj5

Temp  Population  Year  Percent
one    1.92        34.3  2024     57.0
two    1.85        31.4  2020     25.0
three  1.74        28.5  2018      NaN
four   1.72        25.6  2015     30.0
five   1.69        23.4  2012      NaN

In [ ]:
usernames={"Ali":"ali2001", "Vali":"vali#24", "Hasan":"hasan$@","Husan":"Husan_77_11"}
emails={"Ali":"alirasulov2@gmail.com","Vali":"vali_2001@gmail.com","Hasan":'hasan23@gmail.com',"Husan":"husan7711@gmail.com"}

data={
    "username":usernames,
    "emails":emails
}

response_data=pd.DataFrame(data)

In [ ]:
response_data

username                 emails
Ali        ali2001  alirasulov2@gmail.com
Vali       vali#24    vali_2001@gmail.com
Hasan      hasan$@      hasan23@gmail.com
Husan  Husan_77_11    husan7711@gmail.com

In [ ]:
new_indeks=pd.Index(["Vali","Husan","Sardor"])


In [ ]:
new_indeks.isin(response_data.index)

array([ True,  True, False])

In [ ]:
response_data.index.difference(new_indeks)

Index(['Ali', 'Hasan'], dtype='object')

In [ ]:
new_indeks.difference(response_data.index)

Index(['Sardor'], dtype='object')

In [ ]:
response_data.index.union(new_indeks)

Index(['Ali', 'Hasan', 'Husan', 'Sardor', 'Vali'], dtype='object')

In [ ]:
response_data

username                 emails
Ali        ali2001  alirasulov2@gmail.com
Vali       vali#24    vali_2001@gmail.com
Hasan      hasan$@      hasan23@gmail.com
Husan  Husan_77_11    husan7711@gmail.com

In [ ]:
response_data.index.delete(2)

Index(['Ali', 'Vali', 'Husan'], dtype='object')

In [ ]:
response_data.drop("Husan")

username                 emails
Ali    ali2001  alirasulov2@gmail.com
Vali   vali#24    vali_2001@gmail.com
Hasan  hasan$@      hasan23@gmail.com

In [ ]:
obj6={
    "Year":[2024,2020,2018,2015,2012],
    "Population":[34.3,31.4,28.5,25.6,23.4],
    "Temp":[1.92,1.85,1.74,1.72,1.69],
    "Density":[1,2,6,3,7]
}

r_obj=pd.DataFrame(obj6)

In [ ]:
r_obj

Year  Population  Temp  Density
0  2024        34.3  1.92        1
1  2020        31.4  1.85        2
2  2018        28.5  1.74        6
3  2015        25.6  1.72        3
4  2012        23.4  1.69        7

In [ ]:
r_obj.drop("Temp", axis="columns", inplace=True)
r_obj

Year  Population  Density
0  2024        34.3        1
1  2020        31.4        2
2  2018        28.5        6
3  2015        25.6        3
4  2012        23.4        7

In [ ]:
obj=pd.Series(np.arange(8.), index=["a","b","c","d","e","f","g","h"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
f    5.0
g    6.0
h    7.0
dtype: float64

In [ ]:
obj["a"]

0.0

In [ ]:
obj[["a"]]

a    0.0
dtype: float64

In [ ]:
obj[2:5]

c    2.0
d    3.0
e    4.0
dtype: float64

In [ ]:
obj["a":"d"]

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [ ]:
uz={2022:32.4,2020:31.5,2018:30.6,2016:30.1,2014:28.4}
tj={2022:35.4,2020:37.5,2018:21.6,2016:22.1,2014:29.4}
kq={2022:33.4,2020:36.5,2018:23.6,2016:23.1,2014:20.4}
qz={2022:31.4,2020:30.5,2018:25.6,2016:21.1,2014:21.4}
tr={2022:30.4,2020:35.5,2018:26.6,2016:24.1,2014:22.4}

result_df=pd.DataFrame(
    {
    "Uzbekistan":uz,
    "Tajikistan":tj,
    "Kazakhstan":kq,
    "Kyrgizstan":qz,
    "Turkmenistan":tr
})
result_df

Uzbekistan  Tajikistan  Kazakhstan  Kyrgizstan  Turkmenistan
2022        32.4        35.4        33.4        31.4          30.4
2020        31.5        37.5        36.5        30.5          35.5
2018        30.6        21.6        23.6        25.6          26.6
2016        30.1        22.1        23.1        21.1          24.1
2014        28.4        29.4        20.4        21.4          22.4

In [ ]:
result_df["Uzbekistan"].to_numpy()

array([32.4, 31.5, 30.6, 30.1, 28.4])

In [ ]:
result_df[2:]

Uzbekistan  Tajikistan  Kazakhstan  Kyrgizstan  Turkmenistan
2018        30.6        21.6        23.6        25.6          26.6
2016        30.1        22.1        23.1        21.1          24.1
2014        28.4        29.4        20.4        21.4          22.4

In [ ]:
result_df>7

Uzbekistan  Tajikistan  Kazakhstan  Kyrgizstan  Turkmenistan
2022        True        True        True        True          True
2020        True        True        True        True          True
2018        True        True        True        True          True
2016        True        True        True        True          True
2014        True        True        True        True          True

In [ ]:
result_df[["Uzbekistan"]][result_df["Uzbekistan"]>27]

Uzbekistan
2022        32.4
2020        31.5
2018        30.6
2016        30.1
2014        28.4

In [ ]:
result_df["Uzbekistan"]>27

2022    True
2020    True
2018    True
2016    True
2014    True
Name: Uzbekistan, dtype: bool

In [ ]:
new_df=result_df.transpose(copy=True)
new_df

2022  2020  2018  2016  2014
Uzbekistan    32.4  31.5  30.6  30.1  28.4
Tajikistan    35.4  37.5  21.6  22.1  29.4
Kazakhstan    33.4  36.5  23.6  23.1  20.4
Kyrgizstan    31.4  30.5  25.6  21.1  21.4
Turkmenistan  30.4  35.5  26.6  24.1  22.4

In [ ]:
new_df[new_df[2016]>23]

2022  2020  2018  2016  2014
Uzbekistan    32.4  31.5  30.6  30.1  28.4
Kazakhstan    33.4  36.5  23.6  23.1  20.4
Turkmenistan  30.4  35.5  26.6  24.1  22.4

In [ ]:
result_df.loc[[2014,2018]]

Uzbekistan  Tajikistan  Kazakhstan  Kyrgizstan  Turkmenistan
2014        28.4        29.4        20.4        21.4          22.4
2018        30.6        21.6        23.6        25.6          26.6

In [ ]:
result_df.loc[[2018]]

Uzbekistan  Tajikistan  Kazakhstan  Kyrgizstan  Turkmenistan
2018        30.6        21.6        23.6        25.6          26.6

In [ ]:
result_df.iloc[[0,2]]

Uzbekistan  Tajikistan  Kazakhstan  Kyrgizstan  Turkmenistan
2022        32.4        35.4        33.4        31.4          30.4
2018        30.6        21.6        23.6        25.6          26.6

In [ ]:
result_df.at[2018,"Uzbekistan"]

30.6

In [ ]:
result_df.at[2014,"Tajikistan"]-result_df.at[2014,"Turkmenistan"]

7.0

In [ ]:
result_df.iat[2,1]

21.6

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
something=pd.Series(range(4), index=["f","c","e","a"])
something

f    0
c    1
e    2
a    3
dtype: int64

In [ ]:
something.sort_index()

a    3
c    1
e    2
f    0
dtype: int64

In [ ]:
something.sort_values()

f    0
c    1
e    2
a    3
dtype: int64

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/Azure/carprice/master/dataset/carprice.csv")
df.head()

<script src="https://gist.github.com/noamross/e5d3e859aa0c794be10b.js"></script>


symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 ?  alfa-romero       gas        std          two   
1          3                 ?  alfa-romero       gas        std          two   
2          1                 ?  alfa-romero       gas        std          two   
3          2               164         audi       gas        std         four   
4          2               164         audi       gas        std         four   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21   
1         mpfi  3.47    2.68               9.0        111      5000       21   
2         mpfi  2.68    3.47               9.0        154      5000       19   
3         mpfi  3.19    3.40              10.0        102      5500       24   
4         mpfi  3.19    3.40               8.0        115      5500       18   

   highway-mpg  price  
0           27  13495  
1           27  16500  
2           26  16500  
3           30  13950  
4           22  17450  

[5 rows x 26 columns]

In [ ]:
from google.colab import files

In [ ]:
uploaded = files.upload()

Saving cars.csv to cars.csv


In [ ]:
car_df=pd.read_csv("cars.csv")
car_df

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [ ]:
car_df.shape

(32, 12)

In [ ]:
car_df.tail()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  \
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.9   1   1     5   
28  Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5   
29    Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.5   0   1     5   
30   Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.6   0   1     5   
31      Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.6   1   1     4   

    carb  
27     2  
28     4  
29     6  
30     8  
31     2

In [ ]:
car_df.sample(7)

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
7          Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4   
8           Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0     4   
9           Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0     4   
21  Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3   
28    Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5   
24  Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3   
22       AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3   

    carb  
7      2  
8      2  
9      4  
21     2  
28     4  
24     2  
22     2

In [ ]:
car_df.info

<bound method DataFrame.info of              Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2  >