<a href="https://colab.research.google.com/github/baxronovferuz1/DataScience_Np/blob/main/Numpy_Pandas_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world,again")

hello world,again


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import seaborn as sns
import torch
import tensorflow as tf
import keras

In [ ]:
np.__version__

'1.26.4'

In [ ]:
import torch

torch.cuda.is_available()

True

In [ ]:
import numpy as np

In [ ]:
my_list=list(range(20000)) #normal
my_array=np.array(range(20000))  #vektorlashgan



In [ ]:
%time for x in range(10): [i*2 for i in my_list]

CPU times: user 13.3 ms, sys: 0 ns, total: 13.3 ms
Wall time: 13.8 ms


In [ ]:
%time for x in range(10): my_array*2

CPU times: user 1.27 ms, sys: 0 ns, total: 1.27 ms
Wall time: 3.76 ms


In [ ]:
13.8/3.76

3.670212765957447

In [ ]:
import numpy as np

In [ ]:
list1=[1,4,2,4.5,6,0]
arr1=np.array(list1)

In [ ]:
arr1

array([1. , 4. , 2. , 4.5, 6. , 0. ])

In [ ]:
import numpy as np

In [ ]:
tuple1=(7,5,3.2,5,8,1)
array2=np.array(tuple1)

In [ ]:
array2

array([7. , 5. , 3.2, 5. , 8. , 1. ])

In [ ]:
arr1.ndim #ndim-array size

1

In [ ]:
array2.ndim

1

In [ ]:
import numpy as np

In [ ]:
data3=[[1,4,2,5],[7,1,3,8]]
arr3=np.array(data3)

In [ ]:
arr3

array([[1, 4, 2, 5],
       [7, 1, 3, 8]])

In [ ]:
arr3.ndim

2

In [ ]:
arr3.shape

(2, 4)

In [ ]:
arr3.size

8

In [ ]:
import numpy as np

In [ ]:
array4=np.zeros((2,4))
array4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
array4=np.ones((2,4))
array4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr5=np.array([5,2,9,0,3], dtype=np.float64)
arr5

array([5., 2., 9., 0., 3.])

In [ ]:
arr6=np.array([3,2,4,5,8], dtype=np.int32)
arr6

array([3, 2, 4, 5, 8], dtype=int32)

In [ ]:
arr5.dtype

dtype('float64')

In [ ]:
arr7=np.array([1,2,4,5,6]) #avtomatic -int64 type
arr7

array([1, 2, 4, 5, 6])

In [ ]:
arr7.dtype

dtype('int64')

In [ ]:
float_array=arr7.astype(np.float64)
float_array.dtype

dtype('float64')

In [ ]:
arr8=np.array([1.2,3.2,4.5,6.5])

In [ ]:
arr8.dtype

dtype('float64')

In [ ]:
int_arr=arr8.astype(np.int64)

In [ ]:
int_arr.dtype

dtype('int64')

In [ ]:
arr9=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr9

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr9[1,1]

5

In [ ]:
arr10=arr9[2,1:3]
arr10

array([8, 9])

In [ ]:
arr10=np.array(["Ali","Vali","Abdusamad","Hasan","Husan","Bekzod","Shohruh"])


In [ ]:
r_data=np.random.randn(7,3)

In [ ]:
r_data

array([[ 0.47586549, -0.50118118, -0.30165911],
       [ 1.4099227 ,  0.36312282, -1.2895044 ],
       [-0.31525302, -1.32834907,  0.26379727],
       [ 0.92372834, -1.05435786,  1.74970365],
       [-0.23962443, -0.60707214, -1.12318633],
       [ 1.28102636,  0.5164728 ,  0.77598974],
       [ 1.37305013,  0.13706048,  0.43234968]])

In [ ]:
r_data[arr10=="Husan"]

array([[-0.23962443, -0.60707214, -1.12318633]])

In [ ]:
r_data[arr10 != "Vali"]

array([[ 0.47586549, -0.50118118, -0.30165911],
       [-0.31525302, -1.32834907,  0.26379727],
       [ 0.92372834, -1.05435786,  1.74970365],
       [-0.23962443, -0.60707214, -1.12318633],
       [ 1.28102636,  0.5164728 ,  0.77598974],
       [ 1.37305013,  0.13706048,  0.43234968]])

In [ ]:
r_data[~(arr10=="Bekzod")]

array([[ 0.47586549, -0.50118118, -0.30165911],
       [ 1.4099227 ,  0.36312282, -1.2895044 ],
       [-0.31525302, -1.32834907,  0.26379727],
       [ 0.92372834, -1.05435786,  1.74970365],
       [-0.23962443, -0.60707214, -1.12318633],
       [ 1.37305013,  0.13706048,  0.43234968]])

In [ ]:
arr11=(arr10=="Ali") | (arr10=="Vali")
arr11

array([ True,  True, False, False, False, False, False])

In [ ]:
r_data[arr11]

array([[ 0.47586549, -0.50118118, -0.30165911],
       [ 1.4099227 ,  0.36312282, -1.2895044 ]])

In [ ]:
r_data

array([[ 0.47586549, -0.50118118, -0.30165911],
       [ 1.4099227 ,  0.36312282, -1.2895044 ],
       [-0.31525302, -1.32834907,  0.26379727],
       [ 0.92372834, -1.05435786,  1.74970365],
       [-0.23962443, -0.60707214, -1.12318633],
       [ 1.28102636,  0.5164728 ,  0.77598974],
       [ 1.37305013,  0.13706048,  0.43234968]])

In [ ]:
r_data[r_data<0]

array([-0.50118118, -0.30165911, -1.2895044 , -0.31525302, -1.32834907,
       -1.05435786, -0.23962443, -0.60707214, -1.12318633])

In [ ]:
r_data[r_data<0]=0

In [ ]:
r_data

array([[0.47586549, 0.        , 0.        ],
       [1.4099227 , 0.36312282, 0.        ],
       [0.        , 0.        , 0.26379727],
       [0.92372834, 0.        , 1.74970365],
       [0.        , 0.        , 0.        ],
       [1.28102636, 0.5164728 , 0.77598974],
       [1.37305013, 0.13706048, 0.43234968]])

In [ ]:
arr12=np.arange(6).reshape(3,2)

In [ ]:
arr12

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr12.T #Transpose

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
np.dot(arr12,arr12.T)

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

In [ ]:
import numpy as np

In [ ]:
arr13=np.arange(8)

In [ ]:
np.sqrt(arr13) #Unary-sqrt,square,exp,log,modf,sign,isnan

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [ ]:
np.square(arr13)

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [ ]:
np.exp(arr13)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [ ]:
np.log(arr13)

<ipython-input-6-807d863ebc7e>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr13)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015])

In [ ]:
np.log(arr13[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015])

In [ ]:
arr14=np.random.randn(5)
arr14

array([-1.2019784 ,  0.87481513,  0.25801803, -0.78428618,  0.19160698])

In [ ]:
b_arr,q_arr=np.modf(arr14)

In [ ]:
print(b_arr)
print(q_arr)

[-0.2019784   0.87481513  0.25801803 -0.78428618  0.19160698]
[-1.  0.  0. -0.  0.]


In [ ]:
np.sign(arr14)

array([-1.,  1.,  1., -1.,  1.])

In [ ]:
np.isnan(arr14)

array([False, False, False, False, False])

In [ ]:
arr14[1]=np.NaN

In [ ]:
np.isnan(arr14)

array([False,  True, False, False, False])

In [ ]:
arr15=np.random.randn(5)
arr16=np.random.randn(5)

In [ ]:
np.add(arr15,arr16) #Binary-add,multiply,maximum...

array([-0.67949659, -0.57622437,  2.35193888,  1.00664985, -2.30427755])

In [ ]:
arr15+arr16

array([-0.67949659, -0.57622437,  2.35193888,  1.00664985, -2.30427755])

In [ ]:
np.multiply(arr15,arr16)

array([-0.7632123 , -0.81743198,  0.64796804, -0.56725696, -0.48232697])

In [ ]:
np.maximum(arr15,arr16)

array([0.59761034, 0.66080331, 2.03325357, 1.40919078, 0.19313099])

In [ ]:
arr15

array([ 0.59761034, -1.23702768,  2.03325357,  1.40919078, -2.49740853])

In [ ]:
arr16

array([-1.27710692,  0.66080331,  0.31868531, -0.40254092,  0.19313099])

In [ ]:
x_arr=np.array([1.1,1.2,1.3,1.4,1.5])
y_arr=np.array([2.1,2.2,2.3,2.4,2.5])


In [ ]:
cond=np.array([True,False,True,True,False])

In [ ]:
r_arr=np.where(cond,x_arr,y_arr)
r_arr

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [ ]:
arr=np.random.randn(3,3)
arr

array([[ 1.97028118,  0.14300352,  0.52961907],
       [-0.2465072 , -0.09380681,  0.62256699],
       [ 1.46297638,  0.09431839,  0.39675445]])

In [ ]:
result=np.where(arr<0,-1,1)
result

array([[ 1,  1,  1],
       [-1, -1,  1],
       [ 1,  1,  1]])

In [ ]:
arr17=np.random.randn(6,4)
arr17

array([[-0.24332698, -1.53945971, -0.51911703,  0.06716126],
       [-1.32102032,  0.81448664, -0.44454831,  0.0097889 ],
       [ 0.19907587, -0.56617042, -0.39279017,  1.03718558],
       [ 1.10382281,  0.05465317,  0.80834391,  1.33934714],
       [-1.68169702,  0.37352933,  1.11895168,  0.9918056 ],
       [-0.41669942, -1.1587718 ,  0.55296736, -2.10538208]])

In [ ]:
arr17.sum()

5.544569559166768

In [ ]:
arr17.sum(axis=1) #by row

array([ 0.34614457,  0.34245171,  0.24698038,  2.36459896, -0.73338571,
        2.97777964])

In [ ]:
arr17.sum(axis=0) #by column

array([ 0.13381732,  6.75976002, -1.03574966, -0.31325812])

In [ ]:
np.mean(arr17)

-0.07991100015101295

In [ ]:
arr17.mean()

-0.07991100015101295

In [ ]:
arr17.mean(axis=1)

array([-0.55868561, -0.23532327,  0.06932521,  0.82654176,  0.2006474 ,
       -0.78197149])

In [ ]:
arr17.mean(axis=0)

array([-0.39330751, -0.33695546,  0.18730124,  0.22331773])

In [ ]:
arr18=np.arange(6)
arr18

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr18.cumsum()

array([ 0,  1,  3,  6, 10, 15])

In [ ]:
arr19=np.random.randn(6)
arr19

array([-0.52103461,  0.93784467, -0.43476107,  2.03529266, -0.18894129,
       -0.67234901])

In [ ]:
sort_arr=np.sort(arr19)
sort_arr

array([-0.67234901, -0.52103461, -0.43476107, -0.18894129,  0.93784467,
        2.03529266])

In [ ]:
reverse_sort=-np.sort(-arr19) #reverse sort

In [ ]:
reverse_sort

array([ 2.03529266,  0.93784467, -0.18894129, -0.43476107, -0.52103461,
       -0.67234901])

In [ ]:
arr20=np.random.randn(3,4)
arr20

array([[-0.80863969,  0.86943897,  0.3678431 , -0.30254195],
       [ 0.24058725,  0.64709697,  0.86422134, -0.90795647],
       [ 0.47389365, -0.51628005,  0.67993507,  0.30687938]])

In [ ]:
row_sort=np.sort(arr20,axis=0)
row_sort

array([[-0.80863969, -0.51628005,  0.3678431 , -0.90795647],
       [ 0.24058725,  0.64709697,  0.67993507, -0.30254195],
       [ 0.47389365,  0.86943897,  0.86422134,  0.30687938]])

In [ ]:
column_sort=np.sort(arr20,axis=0)
column_sort

array([[-0.80863969, -0.51628005,  0.3678431 , -0.90795647],
       [ 0.24058725,  0.64709697,  0.67993507, -0.30254195],
       [ 0.47389365,  0.86943897,  0.86422134,  0.30687938]])

In [ ]:
arr21=np.array([1,3,2,3,4,8,4,6,1])


In [ ]:
np.unique(arr21)

array([1, 2, 3, 4, 6, 8])

In [ ]:
arr22=np.array([1,3,2,3,4,8,4,6,1])
arr23=np.array([0,1,2,3])

In [ ]:
result_arr=np.in1d(arr22,arr23)
result_arr

array([ True,  True,  True,  True, False, False, False, False,  True])

In [ ]:
np.setdiff1d(arr22,arr23)

array([4, 6, 8])

In [ ]:
import numpy as np

In [ ]:
arr24=np.arange(10)
np.save("data",arr24)


In [ ]:
arr24_=np.load("data.npy")
arr24_

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr25=np.arange(15)


In [ ]:
np.savez("array",a=arr24,b=arr25)


In [ ]:
arrays=np.load("array.npz")
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.savez_compressed("array_comp", a=arr24, b=arr25)

In [ ]:
import pandas as pd
import numpy as np
from pandas import Series

In [ ]:
obj=Series([1,4,6.7,5.9,3])
type(obj)

In [ ]:
print(obj)

0    1.0
1    4.0
2    6.7
3    5.9
4    3.0
dtype: float64


In [ ]:
obj.values

array([1. , 4. , 6.7, 5.9, 3. ])

In [ ]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
obj[2]

6.7

In [ ]:
obj1=Series([1,4,6.7,5.9,3], index=["a","b","c","d","e"])
print(obj1)

a    1.0
b    4.0
c    6.7
d    5.9
e    3.0
dtype: float64


In [ ]:
obj1.values


array([1. , 4. , 6.7, 5.9, 3. ])

In [ ]:
obj1.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [ ]:
obj1["a"]

1.0

In [ ]:
obj1[obj1<4]

a    1.0
e    3.0
dtype: float64

In [ ]:
obj1*2

a     2.0
b     8.0
c    13.4
d    11.8
e     6.0
dtype: float64

In [ ]:
obj2={"Ali":2001,"Vali":2002,"Hasan":1999,"Husan":1998}
result_obj=Series(obj2)
result_obj

Ali      2001
Vali     2002
Hasan    1999
Husan    1998
dtype: int64

In [ ]:
format_obj=["Vali","Husan","Ali","Hasan","Rustam","Xurshid"]

In [ ]:
obj3=Series(obj2, index=format_obj)

In [ ]:
obj3

Vali       2002.0
Husan      1998.0
Ali        2001.0
Hasan      1999.0
Rustam        NaN
Xurshid       NaN
dtype: float64

In [ ]:
obj3.isnull()

Vali       False
Husan      False
Ali        False
Hasan      False
Rustam      True
Xurshid     True
dtype: bool

In [ ]:
obj3.notnull()

Vali        True
Husan       True
Ali         True
Hasan       True
Rustam     False
Xurshid    False
dtype: bool

In [ ]:
obj3.index.name="Year of birth"

In [ ]:
obj3

Year of birth
Vali       2002.0
Husan      1998.0
Ali        2001.0
Hasan      1999.0
Rustam        NaN
Xurshid       NaN
dtype: float64

In [ ]:
obj3.name="User information"

In [ ]:
obj3

Year of birth
Vali       2002.0
Husan      1998.0
Ali        2001.0
Hasan      1999.0
Rustam        NaN
Xurshid       NaN
Name: User information, dtype: float64

In [ ]:
obj4={
    "Year":[2024,2020,2018,2015,2012],
    "Population":[34.3,31.4,28.5,25.6,23.4],
    "Temp":[1.92,1.85,1.74,1.72,1.69]
}

r_obj=pd.DataFrame(obj4)

In [ ]:
r_obj

Year  Population  Temp
0  2024        34.3  1.92
1  2020        31.4  1.85
2  2018        28.5  1.74
3  2015        25.6  1.72
4  2012        23.4  1.69

In [ ]:
r_obj.head(3)

Year  Population  Temp
0  2024        34.3  1.92
1  2020        31.4  1.85
2  2018        28.5  1.74

In [ ]:
r_obj.shape

(5, 3)

In [ ]:
obj5=pd.DataFrame(obj4, columns=["Temp","Population","Year","Percent"])
obj5

Temp  Population  Year Percent
0  1.92        34.3  2024     NaN
1  1.85        31.4  2020     NaN
2  1.74        28.5  2018     NaN
3  1.72        25.6  2015     NaN
4  1.69        23.4  2012     NaN

In [ ]:
obj5=pd.DataFrame(obj4, columns=["Temp","Population","Year","Percent"], index=["one","two","three","four","five"])

In [ ]:
obj5

Temp  Population  Year Percent
one    1.92        34.3  2024     NaN
two    1.85        31.4  2020     NaN
three  1.74        28.5  2018     NaN
four   1.72        25.6  2015     NaN
five   1.69        23.4  2012     NaN

In [ ]:
obj5.Percent=50
obj5

Temp  Population  Year  Percent
one    1.92        34.3  2024       50
two    1.85        31.4  2020       50
three  1.74        28.5  2018       50
four   1.72        25.6  2015       50
five   1.69        23.4  2012       50

In [ ]:
obj6=pd.Series([25,30,57], index=["two","four","one"])
obj6

two     25
four    30
one     57
dtype: int64

In [ ]:
obj5.Percent=obj6
obj5

Temp  Population  Year  Percent
one    1.92        34.3  2024     57.0
two    1.85        31.4  2020     25.0
three  1.74        28.5  2018      NaN
four   1.72        25.6  2015     30.0
five   1.69        23.4  2012      NaN

In [ ]:
usernames={"Ali":"ali2001", "Vali":"vali#24", "Hasan":"hasan$@","Husan":"Husan_77_11"}
emails={"Ali":"alirasulov2@gmail.com","Vali":"vali_2001@gmail.com","Hasan":'hasan23@gmail.com',"Husan":"husan7711@gmail.com"}

data={
    "username":usernames,
    "emails":emails
}

response_data=pd.DataFrame(data)

In [ ]:
response_data

username                 emails
Ali        ali2001  alirasulov2@gmail.com
Vali       vali#24    vali_2001@gmail.com
Hasan      hasan$@      hasan23@gmail.com
Husan  Husan_77_11    husan7711@gmail.com

In [ ]:
new_indeks=pd.Index(["Vali","Husan","Sardor"])


In [ ]:
new_indeks.isin(response_data.index)

array([ True,  True, False])

In [ ]:
response_data.index.difference(new_indeks)

Index(['Ali', 'Hasan'], dtype='object')

In [ ]:
new_indeks.difference(response_data.index)

Index(['Sardor'], dtype='object')

In [ ]:
response_data.index.union(new_indeks)

Index(['Ali', 'Hasan', 'Husan', 'Sardor', 'Vali'], dtype='object')

In [ ]:
response_data

username                 emails
Ali        ali2001  alirasulov2@gmail.com
Vali       vali#24    vali_2001@gmail.com
Hasan      hasan$@      hasan23@gmail.com
Husan  Husan_77_11    husan7711@gmail.com

In [ ]:
response_data.index.delete(2)

Index(['Ali', 'Vali', 'Husan'], dtype='object')

In [ ]:
response_data.drop("Husan")

username                 emails
Ali    ali2001  alirasulov2@gmail.com
Vali   vali#24    vali_2001@gmail.com
Hasan  hasan$@      hasan23@gmail.com

In [ ]:
obj6={
    "Year":[2024,2020,2018,2015,2012],
    "Population":[34.3,31.4,28.5,25.6,23.4],
    "Temp":[1.92,1.85,1.74,1.72,1.69],
    "Density":[1,2,6,3,7]
}

r_obj=pd.DataFrame(obj6)

In [ ]:
r_obj

Year  Population  Temp  Density
0  2024        34.3  1.92        1
1  2020        31.4  1.85        2
2  2018        28.5  1.74        6
3  2015        25.6  1.72        3
4  2012        23.4  1.69        7

In [ ]:
r_obj.drop("Temp", axis="columns", inplace=True)
r_obj

Year  Population  Density
0  2024        34.3        1
1  2020        31.4        2
2  2018        28.5        6
3  2015        25.6        3
4  2012        23.4        7

In [ ]:
obj=pd.Series(np.arange(8.), index=["a","b","c","d","e","f","g","h"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
f    5.0
g    6.0
h    7.0
dtype: float64

In [ ]:
obj["a"]

0.0

In [ ]:
obj[["a"]]

a    0.0
dtype: float64

In [ ]:
obj[2:5]

c    2.0
d    3.0
e    4.0
dtype: float64

In [ ]:
obj["a":"d"]

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [ ]:
uz={2022:32.4,2020:31.5,2018:30.6,2016:30.1,2014:28.4}
tj={2022:35.4,2020:37.5,2018:21.6,2016:22.1,2014:29.4}
kq={2022:33.4,2020:36.5,2018:23.6,2016:23.1,2014:20.4}
qz={2022:31.4,2020:30.5,2018:25.6,2016:21.1,2014:21.4}
tr={2022:30.4,2020:35.5,2018:26.6,2016:24.1,2014:22.4}

result_df=pd.DataFrame(
    {
    "Uzbekistan":uz,
    "Tajikistan":tj,
    "Kazakhstan":kq,
    "Kyrgizstan":qz,
    "Turkmenistan":tr
})
result_df

Uzbekistan  Tajikistan  Kazakhstan  Kyrgizstan  Turkmenistan
2022        32.4        35.4        33.4        31.4          30.4
2020        31.5        37.5        36.5        30.5          35.5
2018        30.6        21.6        23.6        25.6          26.6
2016        30.1        22.1        23.1        21.1          24.1
2014        28.4        29.4        20.4        21.4          22.4

In [ ]:
result_df["Uzbekistan"].to_numpy()

array([32.4, 31.5, 30.6, 30.1, 28.4])

In [ ]:
result_df[2:]

Uzbekistan  Tajikistan  Kazakhstan  Kyrgizstan  Turkmenistan
2018        30.6        21.6        23.6        25.6          26.6
2016        30.1        22.1        23.1        21.1          24.1
2014        28.4        29.4        20.4        21.4          22.4

In [ ]:
result_df>7

Uzbekistan  Tajikistan  Kazakhstan  Kyrgizstan  Turkmenistan
2022        True        True        True        True          True
2020        True        True        True        True          True
2018        True        True        True        True          True
2016        True        True        True        True          True
2014        True        True        True        True          True

In [ ]:
result_df[["Uzbekistan"]][result_df["Uzbekistan"]>27]

Uzbekistan
2022        32.4
2020        31.5
2018        30.6
2016        30.1
2014        28.4

In [ ]:
result_df["Uzbekistan"]>27

2022    True
2020    True
2018    True
2016    True
2014    True
Name: Uzbekistan, dtype: bool

In [ ]:
new_df=result_df.transpose(copy=True)
new_df

2022  2020  2018  2016  2014
Uzbekistan    32.4  31.5  30.6  30.1  28.4
Tajikistan    35.4  37.5  21.6  22.1  29.4
Kazakhstan    33.4  36.5  23.6  23.1  20.4
Kyrgizstan    31.4  30.5  25.6  21.1  21.4
Turkmenistan  30.4  35.5  26.6  24.1  22.4

In [ ]:
new_df[new_df[2016]>23]

2022  2020  2018  2016  2014
Uzbekistan    32.4  31.5  30.6  30.1  28.4
Kazakhstan    33.4  36.5  23.6  23.1  20.4
Turkmenistan  30.4  35.5  26.6  24.1  22.4

In [ ]:
result_df.loc[[2014,2018]]

Uzbekistan  Tajikistan  Kazakhstan  Kyrgizstan  Turkmenistan
2014        28.4        29.4        20.4        21.4          22.4
2018        30.6        21.6        23.6        25.6          26.6

In [ ]:
result_df.loc[[2018]]

Uzbekistan  Tajikistan  Kazakhstan  Kyrgizstan  Turkmenistan
2018        30.6        21.6        23.6        25.6          26.6

In [ ]:
result_df.iloc[[0,2]]

Uzbekistan  Tajikistan  Kazakhstan  Kyrgizstan  Turkmenistan
2022        32.4        35.4        33.4        31.4          30.4
2018        30.6        21.6        23.6        25.6          26.6

In [ ]:
result_df.at[2018,"Uzbekistan"]

30.6

In [ ]:
result_df.at[2014,"Tajikistan"]-result_df.at[2014,"Turkmenistan"]

7.0

In [ ]:
result_df.iat[2,1]

21.6

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
something=pd.Series(range(4), index=["f","c","e","a"])
something

f    0
c    1
e    2
a    3
dtype: int64

In [ ]:
something.sort_index()

a    3
c    1
e    2
f    0
dtype: int64

In [ ]:
something.sort_values()

f    0
c    1
e    2
a    3
dtype: int64

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/Azure/carprice/master/dataset/carprice.csv")
df.head()

<script src="https://gist.github.com/noamross/e5d3e859aa0c794be10b.js"></script>


symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 ?  alfa-romero       gas        std          two   
1          3                 ?  alfa-romero       gas        std          two   
2          1                 ?  alfa-romero       gas        std          two   
3          2               164         audi       gas        std         four   
4          2               164         audi       gas        std         four   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21   
1         mpfi  3.47    2.68               9.0        111      5000       21   
2         mpfi  2.68    3.47               9.0        154      5000       19   
3         mpfi  3.19    3.40              10.0        102      5500       24   
4         mpfi  3.19    3.40               8.0        115      5500       18   

   highway-mpg  price  
0           27  13495  
1           27  16500  
2           26  16500  
3           30  13950  
4           22  17450  

[5 rows x 26 columns]

In [ ]:
from google.colab import files

In [ ]:
uploaded = files.upload()

Saving cars.csv to cars.csv


In [ ]:
car_df=pd.read_csv("cars.csv")
car_df

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [ ]:
car_df.shape

(32, 12)

In [ ]:
car_df.tail()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  \
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.9   1   1     5   
28  Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5   
29    Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.5   0   1     5   
30   Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.6   0   1     5   
31      Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.6   1   1     4   

    carb  
27     2  
28     4  
29     6  
30     8  
31     2

In [ ]:
car_df.sample(7)

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
7          Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4   
8           Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0     4   
9           Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0     4   
21  Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3   
28    Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5   
24  Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3   
22       AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3   

    carb  
7      2  
8      2  
9      4  
21     2  
28     4  
24     2  
22     2

In [ ]:
car_df.info

<bound method DataFrame.info of              Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2  >

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving cars.csv to cars.csv


In [ ]:
car_data=pd.read_csv("cars.csv")
car_data

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [ ]:
car_data.to_excel("newexceldata.xlsx", index=False)

In [ ]:
car_data

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [ ]:
hdf_form=pd.HDFStore("hdf.h5")

In [ ]:
hdf_form.put("carsdata_hdf", car_data)

In [ ]:
hdf_form.keys()

['/carsdata_hdf']

In [ ]:
hdf_form["carsdata_hdf"]

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [ ]:
hdf_form.close()

In [ ]:
hdf_form["carsdata_hdf"]

ClosedFileError: hdf.h5 file is not open!

In [ ]:
hdf_form=pd.HDFStore("hdf.h5")

In [ ]:
hdf_form["carsdata_hdf"]

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [ ]:
web_form=pd.read_html("https://uz.wikipedia.org/wiki/Buxoro")

In [ ]:
len(web_form)


9

In [ ]:
web_form[0]

Buxoro  \
0                                          shahar   
1                                             NaN   
2   39°46′0″N 64°26′0″E / 39.76667°N 64.43333°E   
3                                        Mamlakat   
4                                         Viloyat   
5                                         Hukumat   
6                                         • hokim   
7                                 Ilk eslatilishi   
8                                          Maydon   
9                              Markazi balandligi   
10                                     Iqlim turi   
11                               Rasmiy til(lar)i   
12                                 Aholisi (2010)   
13                                  Milliy tarkib   
14                                 Vaqt mintaqasi   
15                                   Telefon kodi   
16                            Pochta indeks(lar)i   
17                                 Avtomobil kodi   
18                                         Buxoro   

                                             Buxoro.1  
0                                              shahar  
1                                                 NaN  
2       39°46′0″N 64°26′0″E / 39.76667°N 64.43333°E  
3                                         Oʻzbekiston  
4                                     Buxoro viloyati  
5                                             Hukumat  
6                       Jumayev Oʻtkir Hikmatovich[1]  
7                                              VI asr  
8                              143.0 km2 (55.2 kv mi)  
9                                               225 m  
10                                    quruq, mo'tadil  
11                                        oʻzbek tili  
12                             280 000 (2 019-yil)[2]  
13  O'zbeklar Tojiklar Ruslar  Turkmanlar Buxoro y...  
14                                              UTC+5  
15                                                 65  
16                                             2001XX  
17                       20 (1998—2008), 80-84 (2008)  
18                                             Buxoro

In [ ]:
web_form[1]

0                                                  1
0 NaN  Ushbu maqolada Oʻzbekiston milliy ensiklopediy...

In [ ]:
import requests

In [ ]:
r_obj=requests.get("https://openlibrary.org/subjects/python.json?published_in=2010-2024")

In [ ]:
r_obj.status_code

200

In [ ]:
r_obj.json()

{'key': '/subjects/python',
 'name': 'python',
 'subject_type': 'subject',
 'work_count': 113,
 'works': [{'key': '/works/OL2784125W',
   'title': 'Learning Python',
   'edition_count': 22,
   'cover_id': 1312568,
   'cover_edition_key': 'OL9497269M',
   'subject': ['Python (Langage de programmation)',
    'Python (linguagem de programação)',
    'Python (Computer program language)',
    'Python (Lenguaje de programación de computadores)',
    'Langage à objets',
    'Python (programmeertaal)',
    'Object-oriented programming (Computer science)',
    'Python (Computer language)',
    'Interpréteur',
    'Python',
    'COMPUTERS',
    'Programming Languages',
    'Engineering & Applied Sciences',
    'Computer Science',
    'General',
    'Reference',
    'Games',
    'Com051360',
    'Cs.cmp_sc.app_sw',
    'Cs.cmp_sc.prog_lang',
    'Professional, career & trade -> computer science -> programming languages (jr/sr)',
    'Professional, career & trade -> computer science -> general',
 

In [ ]:
pd.DataFrame(r_obj.json())

key    name subject_type  work_count  \
0   /subjects/python  python      subject         113   
1   /subjects/python  python      subject         113   
2   /subjects/python  python      subject         113   
3   /subjects/python  python      subject         113   
4   /subjects/python  python      subject         113   
5   /subjects/python  python      subject         113   
6   /subjects/python  python      subject         113   
7   /subjects/python  python      subject         113   
8   /subjects/python  python      subject         113   
9   /subjects/python  python      subject         113   
10  /subjects/python  python      subject         113   
11  /subjects/python  python      subject         113   

                                                works  
0   {'key': '/works/OL2784125W', 'title': 'Learnin...  
1   {'key': '/works/OL2784127W', 'title': 'Python'...  
2   {'key': '/works/OL16976951W', 'title': 'Think ...  
3   {'key': '/works/OL17795703W', 'title': 'Python...  
4   {'key': '/works/OL2784126W', 'title': 'Program...  
5   {'key': '/works/OL21349037W', 'title': 'Introd...  
6   {'key': '/works/OL15664278W', 'title': 'Head F...  
7   {'key': '/works/OL15667639W', 'title': 'Mining...  
8   {'key': '/works/OL17422847W', 'title': 'Python...  
9   {'key': '/works/OL16223034W', 'title': 'Think ...  
10  {'key': '/works/OL6045694W', 'title': 'Python ...  
11  {'key': '/works/OL23330617W', 'title': 'Making...

In [ ]:
pd.DataFrame(r_obj.json()["works"])

key                                              title  \
0    /works/OL2784125W                                    Learning Python   
1    /works/OL2784127W                                             Python   
2   /works/OL16976951W                                       Think Python   
3   /works/OL17795703W                          Python for bioinformatics   
4    /works/OL2784126W                                 Programming Python   
5   /works/OL21349037W  Introduction to Python for Science and Enginee...   
6   /works/OL15664278W                                  Head First Python   
7   /works/OL15667639W                              Mining the Social Web   
8   /works/OL17422847W                           Python For Data Analysis   
9   /works/OL16223034W                                        Think Stats   
10   /works/OL6045694W                               Python in a Nutshell   
11  /works/OL23330617W                        Making music with computers   

    edition_count   cover_id cover_edition_key  \
0              22  1312568.0        OL9497269M   
1              13   988215.0        OL8942751M   
2              11  7363360.0       OL25763659M   
3              10  8078288.0       OL26385029M   
4              10   805644.0        OL8667192M   
5              10        NaN              None   
6               9  6681113.0       OL24596470M   
7               9  9721114.0       OL24598391M   
8               8  7548132.0              None   
9               8  6956191.0       OL25083068M   
10              8   389166.0        OL7581267M   
11              7        NaN              None   

                                              subject  \
0   [Python (Langage de programmation), Python (li...   
1   [Python (Computer program language), Python (L...   
2   [Computer programming, Software architecture, ...   
3   [Bioinformatics, Python (computer program lang...   
4   [Python (Computer program language), Qa76.73.p...   
5   [Python (computer program language), Engineeri...   
6   [Programming languages (electronic computers),...   
7   [Social networking, Online social networks, Ar...   
8   [Programming languages (Electronic computers),...   
9   [Statistics, Study and teaching, Computer prog...   
10  [Python (Computer program language), Python (p...   
11  [Computer composition, Python (Computer progra...   

                                        ia_collection  lendinglibrary  \
0   [americana, inlibrary, internetarchivebooks, p...           False   
1   [americana, binghamton-ol, inlibrary, internet...           False   
2   [additional_collections, folkscanomy, folkscan...           False   
3                                                  []           False   
4   [americanuniversity-ol, inlibrary, internetarc...           False   
5                                                  []           False   
6   [inlibrary, internetarchivebooks, popularchine...           False   
7    [inlibrary, internetarchivebooks, printdisabled]           False   
8                                                  []           False   
9                                                  []           False   
10  [americanuniversity-ol, drakeuniversity-ol, in...           False   
11                                                 []           False   

    printdisabled lending_edition             lending_identifier  \
0            True     OL37873566M       einfuhrunginpyth0000lutz   
1            True     OL24453347M       pythonpocketrefe00lutz_1   
2            True     OL26455778M                2015ThinkPython   
3           False                                                  
4            True      OL3969544M         programmingpytho00lutz   
5           False                                                  
6            True     OL35343633M       headfirstpythonz0000paul   
7            True     OL26838560M       miningsocialwebd0000russ   
8           False                                             

In [ ]:
import sqlite3 as sql
from pprint import pprint as print
from google.colab import files

In [ ]:
#!wget https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip

--2025-01-28 11:41:37--  https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
Resolving www.sqlitetutorial.net (www.sqlitetutorial.net)... 104.21.30.141, 172.67.172.250, 2606:4700:3037::ac43:acfa, ...
Connecting to www.sqlitetutorial.net (www.sqlitetutorial.net)|104.21.30.141|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 305596 (298K) [application/zip]
Saving to: ‘chinook.zip.2’

chinook.zip.2       100%[===================>] 298.43K  --.-KB/s    in 0.03s   

2025-01-28 11:41:37 (8.79 MB/s) - ‘chinook.zip.2’ saved [305596/305596]



In [ ]:
#db=sql.connect("chinook.db")
#cursor=db.cursor()

In [ ]:
#cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")33cursor.fetchall()

[]

In [ ]:
chinook_file=files.upload()

Saving Chinook_Sqlite.sqlite to Chinook_Sqlite (3).sqlite


In [ ]:
sql_file=sql.connect("Chinook_Sqlite.sqlite")
cursor=sql_file.cursor()

In [ ]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
cursor.fetchall()

[]

In [ ]:
#cursor.execute("SELECT COUNT(*) FROM ")
#cursor.fetchone()

OperationalError: no such table: customers

In [ ]:
!wget https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip

--2025-01-29 05:25:47--  https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
Resolving www.sqlitetutorial.net (www.sqlitetutorial.net)... 172.67.172.250, 104.21.30.141, 2606:4700:3037::6815:1e8d, ...
Connecting to www.sqlitetutorial.net (www.sqlitetutorial.net)|172.67.172.250|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 305596 (298K) [application/zip]
Saving to: ‘chinook.zip’

chinook.zip         100%[===================>] 298.43K  --.-KB/s    in 0.02s   

2025-01-29 05:25:48 (17.9 MB/s) - ‘chinook.zip’ saved [305596/305596]



In [ ]:
import zipfile

zip_path = "chinook.zip"
extract_to = "."

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_to)

print("Opened")



'Opened'


In [ ]:
db=sql.connect("chinook.db")
cursor=db.cursor()

In [ ]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
cursor.fetchall()

[('albums',),
 ('sqlite_sequence',),
 ('artists',),
 ('customers',),
 ('employees',),
 ('genres',),
 ('invoices',),
 ('invoice_items',),
 ('media_types',),
 ('playlists',),
 ('playlist_track',),
 ('tracks',),
 ('sqlite_stat1',)]

In [ ]:
cursor.execute("SELECT COUNT(*) FROM employees")
cursor.fetchone()

(8,)

In [ ]:
cursor.execute("PRAGMA table_info(albums)")
cursor.fetchall()

[(0, 'AlbumId', 'INTEGER', 1, None, 1),
 (1, 'Title', 'NVARCHAR(160)', 1, None, 0),
 (2, 'ArtistId', 'INTEGER', 1, None, 0)]

In [ ]:
import pandas as pd

In [ ]:
ch_df=pd.read_sql("SELECT * FROM employees", db, index_col="EmployeeId")
ch_df

LastName FirstName                Title  ReportsTo  \
EmployeeId                                                       
1              Adams    Andrew      General Manager        NaN   
2            Edwards     Nancy        Sales Manager        1.0   
3            Peacock      Jane  Sales Support Agent        2.0   
4               Park  Margaret  Sales Support Agent        2.0   
5            Johnson     Steve  Sales Support Agent        2.0   
6           Mitchell   Michael           IT Manager        1.0   
7               King    Robert             IT Staff        6.0   
8           Callahan     Laura             IT Staff        6.0   

                      BirthDate             HireDate  \
EmployeeId                                             
1           1962-02-18 00:00:00  2002-08-14 00:00:00   
2           1958-12-08 00:00:00  2002-05-01 00:00:00   
3           1973-08-29 00:00:00  2002-04-01 00:00:00   
4           1947-09-19 00:00:00  2003-05-03 00:00:00   
5           1965-03-03 00:00:00  2003-10-17 00:00:00   
6           1973-07-01 00:00:00  2003-10-17 00:00:00   
7           1970-05-29 00:00:00  2004-01-02 00:00:00   
8           1968-01-09 00:00:00  2004-03-04 00:00:00   

                                Address        City State Country PostalCode  \
EmployeeId                                                                     
1                   11120 Jasper Ave NW    Edmonton    AB  Canada    T5K 2N1   
2                          825 8 Ave SW     Calgary    AB  Canada    T2P 2T3   
3                         1111 6 Ave SW     Calgary    AB  Canada    T2P 5M5   
4                      683 10 Street SW     Calgary    AB  Canada    T2P 5G3   
5                          7727B 41 Ave     Calgary    AB  Canada    T3B 1Y7   
6                  5827 Bowness Road NW     Calgary    AB  Canada    T3B 0C5   
7           590 Columbia Boulevard West  Lethbridge    AB  Canada    T1K 5N8   
8                           923 7 ST NW  Lethbridge    AB  Canada    T1H 1Y8   

                        Phone                Fax                     Email  
EmployeeId                                                                  
1           +1 (780) 428-9482  +1 (780) 428-3457    andrew@chinookcorp.com  
2           +1 (403) 262-3443  +1 (403) 262-3322     nancy@chinookcorp.com  
3           +1 (403) 262-3443  +1 (403) 262-6712      jane@chinookcorp.com  
4           +1 (403) 263-4423  +1 (403) 263-4289  margaret@chinookcorp.com  
5            1 (780) 836-9987   1 (780) 836-9543     steve@chinookcorp.com  
6           +1 (403) 246-9887  +1 (403) 246-9899   michael@chinookcorp.com  
7           +1 (403) 456-9986  +1 (403) 456-8485    robert@chinookcorp.com  
8           +1 (403) 467-3351  +1 (403) 467-8772     laura@chinookcorp.com

In [ ]:
ch_df=pd.read_sql("SELECT * FROM employees LIMIT 5", db, index_col="EmployeeId")
ch_df

LastName FirstName                Title  ReportsTo  \
EmployeeId                                                      
1             Adams    Andrew      General Manager        NaN   
2           Edwards     Nancy        Sales Manager        1.0   
3           Peacock      Jane  Sales Support Agent        2.0   
4              Park  Margaret  Sales Support Agent        2.0   
5           Johnson     Steve  Sales Support Agent        2.0   

                      BirthDate             HireDate              Address  \
EmployeeId                                                                  
1           1962-02-18 00:00:00  2002-08-14 00:00:00  11120 Jasper Ave NW   
2           1958-12-08 00:00:00  2002-05-01 00:00:00         825 8 Ave SW   
3           1973-08-29 00:00:00  2002-04-01 00:00:00        1111 6 Ave SW   
4           1947-09-19 00:00:00  2003-05-03 00:00:00     683 10 Street SW   
5           1965-03-03 00:00:00  2003-10-17 00:00:00         7727B 41 Ave   

                City State Country PostalCode              Phone  \
EmployeeId                                                         
1           Edmonton    AB  Canada    T5K 2N1  +1 (780) 428-9482   
2            Calgary    AB  Canada    T2P 2T3  +1 (403) 262-3443   
3            Calgary    AB  Canada    T2P 5M5  +1 (403) 262-3443   
4            Calgary    AB  Canada    T2P 5G3  +1 (403) 263-4423   
5            Calgary    AB  Canada    T3B 1Y7   1 (780) 836-9987   

                          Fax                     Email  
EmployeeId                                               
1           +1 (780) 428-3457    andrew@chinookcorp.com  
2           +1 (403) 262-3322     nancy@chinookcorp.com  
3           +1 (403) 262-6712      jane@chinookcorp.com  
4           +1 (403) 263-4289  margaret@chinookcorp.com  
5            1 (780) 836-9543     steve@chinookcorp.com

In [ ]:
ch_df=pd.read_sql("SELECT Lastname,BirthDate,City,Phone FROM employees", db)
ch_df.head()


LastName            BirthDate      City              Phone
0    Adams  1962-02-18 00:00:00  Edmonton  +1 (780) 428-9482
1  Edwards  1958-12-08 00:00:00   Calgary  +1 (403) 262-3443
2  Peacock  1973-08-29 00:00:00   Calgary  +1 (403) 262-3443
3     Park  1947-09-19 00:00:00   Calgary  +1 (403) 263-4423
4  Johnson  1965-03-03 00:00:00   Calgary   1 (780) 836-9987

In [ ]:
command="SELECT FirstName,Title,City,Phone FROM employees"
ch_df=pd.read_sql(command,db)
ch_df

FirstName                Title        City              Phone
0    Andrew      General Manager    Edmonton  +1 (780) 428-9482
1     Nancy        Sales Manager     Calgary  +1 (403) 262-3443
2      Jane  Sales Support Agent     Calgary  +1 (403) 262-3443
3  Margaret  Sales Support Agent     Calgary  +1 (403) 263-4423
4     Steve  Sales Support Agent     Calgary   1 (780) 836-9987
5   Michael           IT Manager     Calgary  +1 (403) 246-9887
6    Robert             IT Staff  Lethbridge  +1 (403) 456-9986
7     Laura             IT Staff  Lethbridge  +1 (403) 467-3351

In [ ]:
ch_df=pd.read_sql("SELECT Lastname,BirthDate,City,Phone FROM employees ORDER BY City", db)
ch_df

LastName            BirthDate        City              Phone
0   Edwards  1958-12-08 00:00:00     Calgary  +1 (403) 262-3443
1   Peacock  1973-08-29 00:00:00     Calgary  +1 (403) 262-3443
2      Park  1947-09-19 00:00:00     Calgary  +1 (403) 263-4423
3   Johnson  1965-03-03 00:00:00     Calgary   1 (780) 836-9987
4  Mitchell  1973-07-01 00:00:00     Calgary  +1 (403) 246-9887
5     Adams  1962-02-18 00:00:00    Edmonton  +1 (780) 428-9482
6      King  1970-05-29 00:00:00  Lethbridge  +1 (403) 456-9986
7  Callahan  1968-01-09 00:00:00  Lethbridge  +1 (403) 467-3351

In [ ]:
dic_db="SELECT DISTINCT City FROM employees"
cursor.execute(dic_db)
cursor.fetchall()

[('Edmonton',), ('Calgary',), ('Lethbridge',)]

In [ ]:
where_db='SELECT * FROM employees WHERE Lastname="Johnson"'
pd.read_sql(where_db,db)

EmployeeId LastName FirstName                Title  ReportsTo  \
0           5  Johnson     Steve  Sales Support Agent          2   

             BirthDate             HireDate       Address     City State  \
0  1965-03-03 00:00:00  2003-10-17 00:00:00  7727B 41 Ave  Calgary    AB   

  Country PostalCode             Phone               Fax  \
0  Canada    T3B 1Y7  1 (780) 836-9987  1 (780) 836-9543   

                   Email  
0  steve@chinookcorp.com

In [ ]:
where_db='SELECT * FROM employees WHERE Title="IT Staff" OR Title="Sales Manager" ORDER BY LastName'
pd.read_sql(where_db, db)

EmployeeId  LastName FirstName          Title  ReportsTo  \
0           8  Callahan     Laura       IT Staff          6   
1           2   Edwards     Nancy  Sales Manager          1   
2           7      King    Robert       IT Staff          6   

             BirthDate             HireDate                      Address  \
0  1968-01-09 00:00:00  2004-03-04 00:00:00                  923 7 ST NW   
1  1958-12-08 00:00:00  2002-05-01 00:00:00                 825 8 Ave SW   
2  1970-05-29 00:00:00  2004-01-02 00:00:00  590 Columbia Boulevard West   

         City State Country PostalCode              Phone                Fax  \
0  Lethbridge    AB  Canada    T1H 1Y8  +1 (403) 467-3351  +1 (403) 467-8772   
1     Calgary    AB  Canada    T2P 2T3  +1 (403) 262-3443  +1 (403) 262-3322   
2  Lethbridge    AB  Canada    T1K 5N8  +1 (403) 456-9986  +1 (403) 456-8485   

                    Email  
0   laura@chinookcorp.com  
1   nancy@chinookcorp.com  
2  robert@chinookcorp.com

In [ ]:
db.close()

In [1]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/WilliamJiemesha/CarsCsv/refs/heads/main/cars.csv")
df.head()

mpg   cylinders  cubicinches   hp  weightlbs   time-to-60   year     brand
0  14.0           8          350  165       4209           12   1972       US.
1  31.9           4           89   71       1925           14   1980   Europe.
2  17.0           8          302  140       3449           11   1971       US.
3  15.0           8          400  150       3761           10   1971       US.
4  30.5           4           98   63       2051           17   1978       US.

In [ ]:
df.loc[2, "year"]=np.nan
df.head()

mpg   cylinders  cubicinches   hp  weightlbs   time-to-60   year  \
0  14.0           8          350  165       4209           12   1972   
1  31.9           4           89   71       1925           14   1980   
2  17.0           8          302  140       3449           11   1971   
3  15.0           8          400  150       3761           10   1971   
4  30.5           4           98   63       2051           17   1978   

      brand  hp  hp weightlbs  year  
0       US. NaN           NaN   NaN  
1   Europe. NaN           NaN   NaN  
2       US. NaN           NaN   NaN  
3       US. NaN           NaN   NaN  
4       US. NaN           NaN   NaN

In [ ]:
df.drop("hp weightlbs", axis="columns", inplace=True)


In [ ]:
df

mpg   cylinders  cubicinches   hp  weightlbs   time-to-60   year  \
0    14.0           8          350  165       4209           12   1972   
1    31.9           4           89   71       1925           14   1980   
2    17.0           8          302  140       3449           11   1971   
3    15.0           8          400  150       3761           10   1971   
4    30.5           4           98   63       2051           17   1978   
..    ...         ...          ...  ...        ...          ...    ...   
256  17.0           8          305  130       3840           15   1980   
257  36.1           4           91   60       1800           16   1979   
258  22.0           6          232  112       2835           15   1983   
259  18.0           6          232  100       3288           16   1972   
260  22.0           6          250  105       3353           15   1977   

        brand  year  
0         US.   NaN  
1     Europe.   NaN  
2         US.   NaN  
3         US.   NaN  
4         US.   NaN  
..        ...   ...  
256       US.   NaN  
257    Japan.   NaN  
258       US.   NaN  
259       US.   NaN  
260       US.   NaN  

[261 rows x 9 columns]

In [ ]:
df.loc[3, "brand"]=np.nan
df.head()

mpg   cylinders  cubicinches   hp  weightlbs   time-to-60   year  \
0  14.0           8          350  165       4209           12   1972   
1  31.9           4           89   71       1925           14   1980   
2  17.0           8          302  140       3449           11   1971   
3  15.0           8          400  150       3761           10   1971   
4  30.5           4           98   63       2051           17   1978   

      brand  year  brand  
0       US.   NaN    NaN  
1   Europe.   NaN    NaN  
2       US.   NaN    NaN  
3       US.   NaN    NaN  
4       US.   NaN    NaN

In [ ]:
print(df.columns.tolist())


['mpg', ' cylinders', ' cubicinches', ' hp', ' weightlbs', ' time-to-60', ' year', ' brand', 'year', 'brand']


In [ ]:
df.drop("brand", axis="columns", inplace=True)


In [ ]:
df

mpg   cylinders  cubicinches   hp  weightlbs   time-to-60   year  \
0    14.0           8          350  165       4209           12   1972   
1    31.9           4           89   71       1925           14   1980   
2    17.0           8          302  140       3449           11   1971   
3    15.0           8          400  150       3761           10   1971   
4    30.5           4           98   63       2051           17   1978   
..    ...         ...          ...  ...        ...          ...    ...   
256  17.0           8          305  130       3840           15   1980   
257  36.1           4           91   60       1800           16   1979   
258  22.0           6          232  112       2835           15   1983   
259  18.0           6          232  100       3288           16   1972   
260  22.0           6          250  105       3353           15   1977   

        brand  year  
0         US.   NaN  
1     Europe.   NaN  
2         US.   NaN  
3         US.   NaN  
4         US.   NaN  
..        ...   ...  
256       US.   NaN  
257    Japan.   NaN  
258       US.   NaN  
259       US.   NaN  
260       US.   NaN  

[261 rows x 9 columns]

In [ ]:
df.columns = df.columns.str.strip()

In [ ]:
df

mpg  cylinders cubicinches   hp weightlbs  time-to-60  year     brand  \
0    14.0          8         350  165      4209          12  1972       US.   
1    31.9          4          89   71      1925          14  1980   Europe.   
2    17.0          8         302  140      3449          11  1971       US.   
3    15.0          8         400  150      3761          10  1971       US.   
4    30.5          4          98   63      2051          17  1978       US.   
..    ...        ...         ...  ...       ...         ...   ...       ...   
256  17.0          8         305  130      3840          15  1980       US.   
257  36.1          4          91   60      1800          16  1979    Japan.   
258  22.0          6         232  112      2835          15  1983       US.   
259  18.0          6         232  100      3288          16  1972       US.   
260  22.0          6         250  105      3353          15  1977       US.   

     year  
0     NaN  
1     NaN  
2     NaN  
3     NaN  
4     NaN  
..    ...  
256   NaN  
257   NaN  
258   NaN  
259   NaN  
260   NaN  

[261 rows x 9 columns]

In [ ]:
print(df.columns.tolist())

['mpg', 'cylinders', 'cubicinches', 'hp', 'weightlbs', 'time-to-60', 'year', 'brand', 'year']


In [ ]:
df.loc[3, "brand"]=np.nan
df.head()

mpg  cylinders cubicinches   hp weightlbs  time-to-60  year     brand  \
0  14.0          8         350  165      4209          12  1972       US.   
1  31.9          4          89   71      1925          14  1980   Europe.   
2  17.0          8         302  140      3449          11  1971       US.   
3  15.0          8         400  150      3761          10  1971       NaN   
4  30.5          4          98   63      2051          17  1978       US.   

   year  
0   NaN  
1   NaN  
2   NaN  
3   NaN  
4   NaN

In [ ]:
df.loc[2, "hp"]=np.nan
df.head()

mpg  cylinders cubicinches     hp weightlbs  time-to-60  year     brand  \
0  14.0          8         350  165.0      4209          12  1972       US.   
1  31.9          4          89   71.0      1925          14  1980   Europe.   
2  17.0          8         302    NaN      3449          11  1971       US.   
3  15.0          8         400  150.0      3761          10  1971       NaN   
4  30.5          4          98   63.0      2051          17  1978       US.   

   year  
0   NaN  
1   NaN  
2   NaN  
3   NaN  
4   NaN

In [ ]:
df.loc[1,"weightlbs"]=np.nan
df.head()

mpg  cylinders cubicinches     hp weightlbs  time-to-60  year     brand  \
0  14.0          8         350  165.0      4209          12  1972       US.   
1  31.9          4          89   71.0       NaN          14  1980   Europe.   
2  17.0          8         302    NaN      3449          11  1971       US.   
3  15.0          8         400  150.0      3761          10  1971       NaN   
4  30.5          4          98   63.0      2051          17  1978       US.   

   year  
0   NaN  
1   NaN  
2   NaN  
3   NaN  
4   NaN

In [ ]:
df.head(7)

mpg  cylinders cubicinches     hp weightlbs  time-to-60  year     brand  \
0  14.0          8         350  165.0      4209          12  1972       US.   
1  31.9          4          89   71.0       NaN          14  1980   Europe.   
2  17.0          8         302    NaN      3449          11  1971       US.   
3  15.0          8         400  150.0      3761          10  1971       NaN   
4  30.5          4          98   63.0      2051          17  1978       US.   
5  23.0          8         350  125.0      3900          17  1980       US.   
6  13.0          8         351  158.0      4363          13  1974       US.   

   year  
0   NaN  
1   NaN  
2   NaN  
3   NaN  
4   NaN  
5   NaN  
6   NaN

In [ ]:
df.drop("year", axis="columns", inplace=True)

In [ ]:
df

mpg  cylinders cubicinches     hp weightlbs  time-to-60     brand
0    14.0          8         350  165.0      4209          12       US.
1    31.9          4          89   71.0       NaN          14   Europe.
2    17.0          8         302    NaN      3449          11       US.
3    15.0          8         400  150.0      3761          10       NaN
4    30.5          4          98   63.0      2051          17       US.
..    ...        ...         ...    ...       ...         ...       ...
256  17.0          8         305  130.0      3840          15       US.
257  36.1          4          91   60.0      1800          16    Japan.
258  22.0          6         232  112.0      2835          15       US.
259  18.0          6         232  100.0      3288          16       US.
260  22.0          6         250  105.0      3353          15       US.

[261 rows x 7 columns]

In [ ]:
df.head(7)

mpg  cylinders cubicinches     hp weightlbs  time-to-60     brand
0  14.0          8         350  165.0      4209          12       US.
1  31.9          4          89   71.0       NaN          14   Europe.
2  17.0          8         302    NaN      3449          11       US.
3  15.0          8         400  150.0      3761          10       NaN
4  30.5          4          98   63.0      2051          17       US.
5  23.0          8         350  125.0      3900          17       US.
6  13.0          8         351  158.0      4363          13       US.

In [ ]:
df.isnull()

mpg  cylinders  cubicinches     hp  weightlbs  time-to-60  brand
0    False      False        False  False      False       False  False
1    False      False        False  False       True       False  False
2    False      False        False   True      False       False  False
3    False      False        False  False      False       False   True
4    False      False        False  False      False       False  False
..     ...        ...          ...    ...        ...         ...    ...
256  False      False        False  False      False       False  False
257  False      False        False  False      False       False  False
258  False      False        False  False      False       False  False
259  False      False        False  False      False       False  False
260  False      False        False  False      False       False  False

[261 rows x 7 columns]

In [ ]:
df.isnull().sum()

mpg            0
cylinders      0
cubicinches    0
hp             1
weightlbs      1
time-to-60     0
brand          1
dtype: int64

In [ ]:
df.dropna()

mpg  cylinders cubicinches     hp weightlbs  time-to-60    brand
0    14.0          8         350  165.0      4209          12      US.
4    30.5          4          98   63.0      2051          17      US.
5    23.0          8         350  125.0      3900          17      US.
6    13.0          8         351  158.0      4363          13      US.
7    14.0          8         440  215.0      4312           9      US.
..    ...        ...         ...    ...       ...         ...      ...
256  17.0          8         305  130.0      3840          15      US.
257  36.1          4          91   60.0      1800          16   Japan.
258  22.0          6         232  112.0      2835          15      US.
259  18.0          6         232  100.0      3288          16      US.
260  22.0          6         250  105.0      3353          15      US.

[258 rows x 7 columns]

In [ ]:
df.dropna(axis=1)

mpg  cylinders cubicinches  time-to-60
0    14.0          8         350          12
1    31.9          4          89          14
2    17.0          8         302          11
3    15.0          8         400          10
4    30.5          4          98          17
..    ...        ...         ...         ...
256  17.0          8         305          15
257  36.1          4          91          16
258  22.0          6         232          15
259  18.0          6         232          16
260  22.0          6         250          15

[261 rows x 4 columns]

In [ ]:
df.dropna(axis=1, thresh=10)

mpg  cylinders cubicinches     hp weightlbs  time-to-60     brand
0    14.0          8         350  165.0      4209          12       US.
1    31.9          4          89   71.0       NaN          14   Europe.
2    17.0          8         302    NaN      3449          11       US.
3    15.0          8         400  150.0      3761          10       NaN
4    30.5          4          98   63.0      2051          17       US.
..    ...        ...         ...    ...       ...         ...       ...
256  17.0          8         305  130.0      3840          15       US.
257  36.1          4          91   60.0      1800          16    Japan.
258  22.0          6         232  112.0      2835          15       US.
259  18.0          6         232  100.0      3288          16       US.
260  22.0          6         250  105.0      3353          15       US.

[261 rows x 7 columns]

In [ ]:
df.dropna(subset=["cylinders","brand"])

mpg  cylinders cubicinches     hp weightlbs  time-to-60     brand
0    14.0          8         350  165.0      4209          12       US.
1    31.9          4          89   71.0       NaN          14   Europe.
2    17.0          8         302    NaN      3449          11       US.
4    30.5          4          98   63.0      2051          17       US.
5    23.0          8         350  125.0      3900          17       US.
..    ...        ...         ...    ...       ...         ...       ...
256  17.0          8         305  130.0      3840          15       US.
257  36.1          4          91   60.0      1800          16    Japan.
258  22.0          6         232  112.0      2835          15       US.
259  18.0          6         232  100.0      3288          16       US.
260  22.0          6         250  105.0      3353          15       US.

[260 rows x 7 columns]

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/WilliamJiemesha/CarsCsv/refs/heads/main/cars.csv")
df.head()

mpg   cylinders  cubicinches   hp  weightlbs   time-to-60   year     brand
0  14.0           8          350  165       4209           12   1972       US.
1  31.9           4           89   71       1925           14   1980   Europe.
2  17.0           8          302  140       3449           11   1971       US.
3  15.0           8          400  150       3761           10   1971       US.
4  30.5           4           98   63       2051           17   1978       US.

In [3]:
df

mpg   cylinders  cubicinches   hp  weightlbs   time-to-60   year  \
0    14.0           8          350  165       4209           12   1972   
1    31.9           4           89   71       1925           14   1980   
2    17.0           8          302  140       3449           11   1971   
3    15.0           8          400  150       3761           10   1971   
4    30.5           4           98   63       2051           17   1978   
..    ...         ...          ...  ...        ...          ...    ...   
256  17.0           8          305  130       3840           15   1980   
257  36.1           4           91   60       1800           16   1979   
258  22.0           6          232  112       2835           15   1983   
259  18.0           6          232  100       3288           16   1972   
260  22.0           6          250  105       3353           15   1977   

        brand  
0         US.  
1     Europe.  
2         US.  
3         US.  
4         US.  
..        ...  
256       US.  
257    Japan.  
258       US.  
259       US.  
260       US.  

[261 rows x 8 columns]

In [4]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
256    False
257    False
258    False
259    False
260    False
Length: 261, dtype: bool

In [5]:
df.shape

(261, 8)

In [6]:
df.duplicated().sum()

0

In [7]:
df.drop_duplicates()

mpg   cylinders  cubicinches   hp  weightlbs   time-to-60   year  \
0    14.0           8          350  165       4209           12   1972   
1    31.9           4           89   71       1925           14   1980   
2    17.0           8          302  140       3449           11   1971   
3    15.0           8          400  150       3761           10   1971   
4    30.5           4           98   63       2051           17   1978   
..    ...         ...          ...  ...        ...          ...    ...   
256  17.0           8          305  130       3840           15   1980   
257  36.1           4           91   60       1800           16   1979   
258  22.0           6          232  112       2835           15   1983   
259  18.0           6          232  100       3288           16   1972   
260  22.0           6          250  105       3353           15   1977   

        brand  
0         US.  
1     Europe.  
2         US.  
3         US.  
4         US.  
..        ...  
256       US.  
257    Japan.  
258       US.  
259       US.  
260       US.  

[261 rows x 8 columns]

In [11]:
df

mpg   cylinders  cubicinches   hp  weightlbs   time-to-60   year  \
0    14.0           8          350  165       4209           12   1972   
1    31.9           4           89   71       1925           14   1980   
2    17.0           8          302  140       3449           11   1971   
3    15.0           8          400  150       3761           10   1971   
4    30.5           4           98   63       2051           17   1978   
..    ...         ...          ...  ...        ...          ...    ...   
256  17.0           8          305  130       3840           15   1980   
257  36.1           4           91   60       1800           16   1979   
258  22.0           6          232  112       2835           15   1983   
259  18.0           6          232  100       3288           16   1972   
260  22.0           6          250  105       3353           15   1977   

        brand  
0         US.  
1     Europe.  
2         US.  
3         US.  
4         US.  
..        ...  
256       US.  
257    Japan.  
258       US.  
259       US.  
260       US.  

[261 rows x 8 columns]

In [12]:
df.drop_duplicates(['year'])

KeyError: Index(['year'], dtype='object')

In [13]:
print(df.columns)


Index(['mpg', ' cylinders', ' cubicinches', ' hp', ' weightlbs', ' time-to-60',
       ' year', ' brand'],
      dtype='object')


In [14]:
df.drop_duplicates([" year"])

mpg   cylinders  cubicinches   hp  weightlbs   time-to-60   year  \
0   14.0           8          350  165       4209           12   1972   
1   31.9           4           89   71       1925           14   1980   
2   17.0           8          302  140       3449           11   1971   
4   30.5           4           98   63       2051           17   1978   
6   13.0           8          351  158       4363           13   1974   
9   37.7           4           89   62       2050           17   1982   
10  34.0           4          108   70       2245           17   1983   
11  34.3           4           97   78       2188           16   1981   
12  16.0           8          302  140       4141           14   1975   
18  24.0           4          113   95       2278           16   1973   
22  24.0           6          200   81       3012           18   1977   
27  14.0           8          351  148       4657           14   1976   
77  21.1           4          134   95       2515           15   1979   

       brand  
0        US.  
1    Europe.  
2        US.  
4        US.  
6        US.  
9     Japan.  
10    Japan.  
11   Europe.  
12       US.  
18    Japan.  
22       US.  
27       US.  
77    Japan.

In [19]:
df.replace("Japan.", "Yaponiya")
df.head(20)

mpg   cylinders  cubicinches   hp  weightlbs   time-to-60   year  \
0   14.0           8          350  165       4209           12   1972   
1   31.9           4           89   71       1925           14   1980   
2   17.0           8          302  140       3449           11   1971   
3   15.0           8          400  150       3761           10   1971   
4   30.5           4           98   63       2051           17   1978   
5   23.0           8          350  125       3900           17   1980   
6   13.0           8          351  158       4363           13   1974   
7   14.0           8          440  215       4312            9   1971   
8   25.4           5          183   77       3530           20   1980   
9   37.7           4           89   62       2050           17   1982   
10  34.0           4          108   70       2245           17   1983   
11  34.3           4           97   78       2188           16   1981   
12  16.0           8          302  140       4141           14   1975   
13  11.0           8          350  180       3664           11   1974   
14  19.1           6          225   90                      19   1981   
15  16.9           8          350  155       4360           15   1980   
16  31.8           4           85   65       2020           19   1980   
17  16.0           8          304  150       3433           12   1971   
18  24.0           4          113   95       2278           16   1973   
19  24.0           4          107   90       2430           15   1971   

       brand  
0        US.  
1    Europe.  
2        US.  
3        US.  
4        US.  
5        US.  
6        US.  
7        US.  
8    Europe.  
9     Japan.  
10    Japan.  
11   Europe.  
12       US.  
13       US.  
14       US.  
15       US.  
16    Japan.  
17       US.  
18    Japan.  
19   Europe.

In [20]:
df.rename(columns=str.upper)

MPG   CYLINDERS  CUBICINCHES   HP  WEIGHTLBS   TIME-TO-60   YEAR  \
0    14.0           8          350  165       4209           12   1972   
1    31.9           4           89   71       1925           14   1980   
2    17.0           8          302  140       3449           11   1971   
3    15.0           8          400  150       3761           10   1971   
4    30.5           4           98   63       2051           17   1978   
..    ...         ...          ...  ...        ...          ...    ...   
256  17.0           8          305  130       3840           15   1980   
257  36.1           4           91   60       1800           16   1979   
258  22.0           6          232  112       2835           15   1983   
259  18.0           6          232  100       3288           16   1972   
260  22.0           6          250  105       3353           15   1977   

        BRAND  
0         US.  
1     Europe.  
2         US.  
3         US.  
4         US.  
..        ...  
256       US.  
257    Japan.  
258       US.  
259       US.  
260       US.  

[261 rows x 8 columns]

In [22]:
df.rename(columns={" brand":"Cars brand"}, inplace=True)